### ISSUE TITLE
Ajouter un mot sur la page front.html FR/NL/UK

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#10]
Sous la date de l'exposition Gustav Mesmer, merci d'ajouter Bientôt (FR), Binnenkort (NL) et Soon (UK).

Tatiana aimerait quelque chose d'assez visible.

**Comment by pacomski** [comment]
J'ai besoin de plus de précisions graphique pour "assez visible", (comme le titre, comme les dates, autrement ?).
Pour le moment j'ai mis comme les autres labels du même type qui sont ailleurs sur le site
