### ISSUE TITLE
Problème Inscription Newsletter 

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1031]
Hey ! 

Les inscriptions à la newsletter sur le site web ne fonctionnent malheureusement pas, y-a-t-il moyen de faire quelque chose pour cela ?

**Comment by ninwille** [comment]
Hello, c'est un soucis dans votre compte mailjet, le widget n'est plus connectée à une liste de contacts. 
Il faut aller dans 'contact' -> 'widget d'abonnements' 
Là, à côté du bon widget (je dirais que c'est le 2e qui est utilisé, mais sans certitude), il faut cliquer sur 'gérer'. 
Il faut ensuite sélectionner une liste de contacts dans laquelle s'ajouteront les mails encodés.

**Comment by FredericOszczak** [comment]
Voici le nouveau Widget ! 

<iframe class="mj-w-res-iframe" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://app.mailjet.com/widget/iframe/1iRq/FPa" width="100%"></iframe>

<script type="text/javascript" src="https://app.mailjet.com/statics/js/iframeResizer.min.js"></script>

**Comment by ninwille** [comment]
Hello, il semblerait que ce widget là non plus ne soit pas lié à une liste de contacts... quand tu vas sur "gérer" puis sur le crayon, en haut au milieu il faut sélectionner une liste de contacts.

**Comment by ninwille** [comment]
Par ailleurs, si vous ajoutez du texte il faudra prévoir la version nl et en.

**Comment by FredericOszczak** [comment]
<iframe class="mj-w-res-iframe" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://app.mailjet.com/widget/iframe/1iRq/FPa" width="100%"></iframe>

<script type="text/javascript" src="https://app.mailjet.com/statics/js/iframeResizer.min.js"></script>

**Comment by FredericOszczak** [comment]
Est-ce bon comme cela ?

**Comment by FredericOszczak** [comment]
Si c'est ok je ferais en NL et ENG ! Je ne peux pas faire sans texte il me semble, impossible de refaire le design précédent... quelle galère ce truc !

**Comment by ninwille** [comment]
Oui ça a l'air de fonctionner :) Parfait si tu m'envoies les versions nl et en.
(sinon je pense que tu peux utiliser les précédents et leur ajouter juste une liste de contact).

**Comment by FredericOszczak** [comment]
Hello Nina ! 

Voici le Widget à utiliser pour les trois langues, désolée de te faire rechanger pour le français ! J'ai vraiment zéro compétence à tout ce qui s'approche de pret ou de loin à de l'informatique !! J'espère que ça fonctionne comme cela !

<iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://app.mailjet.com/widget/iframe/1iRq/3p5" width="100%" height="85"></iframe>
