### ISSUE TITLE
[QR] contenus QR

### ISSUE THREAD

**Issue by pacomski** [communicationartetmarges/art-et-marges#1054]
16 QR CODE dans le musée: 3 d'entre eux seront permanents, ne changeront pas en fonction des expos en tout cas: celui de l'accueil, celui de la nouvelle publication 5(bookshop) et celui du laboratoire.

- [x] pour l'accueil : https://youtu.be/lhZhAhCAMRQ
- [x] pour le bookshop : https://youtu.be/0lQeFNZ_B7E
- [x] laboratoire : https://www.youtube.com/watch?v=ZAMyyDHkF1A

lien vers liste des QR Codes : http://artetmarges.be/qr/list.html

**Comment by FredericOszczak** [comment]
Une question : est ce que les contenus ne seront que des vidéos ? ou bien des pages WEB plus complètes avec titres, texte, images etc..  ?

Pour cette première exposition on va être uniquement sur du contenu vidéo normalement. 

Voici d'ailleurs le troisième contenu pour le laboratoire, il y a moyen que la vidéo doive être changée, j'en saurais plus jeudi : [](https://www.youtube.com/watch?v=ZAMyyDHkF1A )

**Comment by FredericOszczak** [comment]
Question : Sera-t-il possible de chiffrer les données ? Pour savoir le nombre de scan effectué sur un QR ?

**Comment by pacomski** [comment]
Pour connaitre un peu ce qu'il se passe sur le site du musée, vous avez un accès Google analytics en interne, et vous avez donc théoriquement accès à toutes les stats de fréquentations. (donc le nombre de visites pour chaque page accessible via QR code)

**Comment by pacomski** [comment]
@FredericOszczak voici un lien vers la liste des qr codes générés jusqu'à présent : http://artetmarges.be/qr/list.html

Ils sont en .svg, vous pouvez donc commencer à les imprimer et les utiliser comme vous le souhaitez pour tester .
Pour les télécharger : clic droit, sauver sous...

Pour les générer, j'ai simplement utilisé https://www.the-qrcode-generator.com/
Le qr code contient les urls des contenus visés (des nouvelles pages du site)

J'attends vos retours et les contenus suivant ;)

**Comment by FredericOszczak** [comment]
Hello Pacôme, 

Oui je reçois bien les notifications par email donc pas la peine de faire des doublons emails. Je ne travaille en revanche pas le lundi. 

Les QR fonctionnent c'est top comme ça ! 

J'ai retrouvé le Google Analytics merci !
