### ISSUE TITLE
Mail de rappel ? 

### ISSUE THREAD

**Issue by pacomski** [communicationartetmarges/art-et-marges#1055]
Il est possible d’envoyer un mail de rappel la veille, est ce que vous souhaitez ceci comme fonctionnalité ? 

si oui, merci de nous envoyer les textes FR/NL/EN qui doivent y figurer ;)

**Comment by FredericOszczak** [comment]
Email de rappel (la veille) :
Objet : Rappel, visite au Art et marges musée DEMAIN ! 

Bonjour ! 
Vous avez réservé une visite au Art et marges musée pour demain ! 
Nous sommes ravis de vous accueillir et prenons toutes les dispositions nécessaires pour vous recevoir dans les meilleures conditions. 
Pour cela, merci de venir à l'heure convenue, avec un masque et un moyen de paiement par carte bancaire. 

À demain ! 

L'équipe du Art et marges musée


Objet : Herinneringsmail - bezoek van het Art et marges museum MORGEN

Goeiedag!
U heeft een bezoek morgen in het Art et marges museum gereserveerd!
Het is ons plezier u te verwelkomen. We zorgen ervoor dat we u in de beste omstandigheden kunnen ontvangen.
Kom hiervoor op het afgesproken tijdstip, met een mondmasker en een creditcard als betaalmiddel.
Tot morgen!


Objet : Reminder, visite at Art et marges museum TOMORROW !

Hello ! 
You have booked a visit at Art et marges museum tomorrow ! 
We are glad to welcoming you with all the best necessary sanitary measures. To respect all, please come on time, with a face mask and a payment method by credit card.

See you tomorrow ! 

The Art et marges museum team
