### ISSUE TITLE
Textes Réservation

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1056]
Hello Pacôme, 

Les textes vont un peu changer, je te renvoie ça quand les trad sont finies.

**Comment by FredericOszczak** [comment]
Titre bouton :
- Réservation visite 
- Reserveer een bezoek  
- Visit booking

Espace 1 :
- "Nombre de visiteur.se.s enfant.s et adulte.s" 
- Aantal bezoekers (kinderen en volwassen). 
- Visitor.s number  (children and adults)

Phrase d’introduction :
- Réservez votre visite en ligne et payez au musée (paiement par carte bancaire préféré). 
Tarifs : Plein 4€, Réduit 2€ (Enfants 7 à 17 ans, Étudiants, Groupes (≥10 personnes), Pensionnés, Carte culture voisins 1,25€ Article 27), Gratuit (1er dimanche du mois, Enfants - 6 ans, Enseignants, Membres ICOM, Brussels card, Museum Pass)
Pour les groupes, merci de contacter la chargée des publics : alix.hubermont@artetmarges.be
- Boek je bezoek online en betaal in het museum (betaling met kaart gewenst). Prijslijst : Individuele bezoeker 4€. Gereduceerde tarieven 2€ (kinderen 7-17 jaar, studenten, groep van min. 10 personen), gepensioneerden), 1,25€ (Artikel 27), Gratis (1ste zondag van de maand, kinderen jonger dan 6 jaar, leraren, ICOM-leden, Brussel-kaart, Museumpas)
Voor groepen kunt u contact opnemen met de Audience Officer: alix.hubermont@artetmarges.be
- Book your visit online and pay at the museum (payment by credit card preferred). Price list : Full 4€, Reduced 2€ (Children, Students, Groups (≥10 persons), Pensioners, Neighbourhood Culture Card 1,25€ Article 27), Free (1st Sunday of the month, Children under 6 years old, Teachers, ICOM Members, Brussels card, Museum Pass)
For groups, thank you to contact the person in charge of publics at alix.hubermont@artetmarges.be

Email de confirmation:
 - Bonjour ! Vous venez de réserver une visite au Art et marges musée le ... à ... Veuillez-vous présenter à l'heure muni d'un masque ainsi que d'un moyen de paiement pour régler votre entrée (paiement par carte bancaire préféré). Le musée est Rue Haute 314, 1000 Bruxelles. En cas d'empêchement pour venir à votre visite, veuillez nous prévenir via info@artetmarges.be ou au +32 (0) 2 533 94 90. Le musée est ouvert du mardi au dimanche de 11h à 18h. Nous vous attendons avec impatience ! À très vite ! L'équipe du Art et marges musée 
-  Hallo! Je hebt een bezoek gereserveerd bij het Art et marges museum op… om ... Gelieve op tijd te komen, met een masker en een betaalmiddel om je toegangsticket af te rekenen (betaling met kaart gewenst). Het adres van het museum is: Hoogstraat 314 - 1000 Brussel. Indien je toch niet op bezoek kunt komen, laat het ons dan weten via info@artetmarges.be of +32 (0) 2 533 94 90.  Het museum is open van dinsdag tot en met zondag tussen 11 en 18 uur.
 We kijken uit naar je komst! Tot ziens! Het team van het Art et marges museum 
- Hello! You just booked a visit to the Art et marges museum on ... at ... Please arrive on time with a face mask and a means of payment for your entrance fees  (payment by credit card preferred). The museum is Rue Haute 314, 1000 Brussels. If you are unable to come to your visit, please let us know via info@artetmarges.be or call us on +32 (0) 2 533 94 90. The museum is open from Tuesday to Sunday from 11 am to 6 pm. We look forward to seeing you! See you soon! The Art et marges museum's team

**Comment by pacomski** [comment]
Je pense que c'est en ordre

il y a juste encore à traduire:

- [ ] Payer en argent comptant à la livraison."

- [ ] Vos données personnelles seront utilisées pour le traitement de votre commande, vous accompagner au cours de votre visite du site web, et pour d’autres raisons décrites dans notre politique de confidentialité."

Il faudrait aussi une page "politique de confidentialité" (pour le rgpd) en trois langues, peut être que vous pouvez contacter un-e autre musée ou institution pour en avoir un modèle ?
