### ISSUE TITLE
Questions concernant la plateforme de réservation

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1064]
Hello Pacôme,
Voici donc tous les textes pour finaliser la plateforme de réservation, avec la réouverture ça tombe à pic ! 

Quelques questions : 
A) Est-il possible de mettre un bouton/lien vers la plateforme de réservation à partir d'INFORMATION - INFORMATIONS PRATIQUES tout en haut en bleu du site web écriture blanche ? 
+ Dans INFORMATION - MESURES SANITAIRES COVID-19 - Modalités de réservation : La réservation s'effectue sur la plateforme suivante : ... N'hésitez pas à envoyer un email à info@artetmarges.be en cas de difficultés
+ Tout en haut de tout le site à côté des boutons réseaux sociaux ? 
CF intégration suivante : 
![Intégration_Plateforme réservation](https://user-images.githubusercontent.com/22938933/100770100-2f67b400-33fd-11eb-9de6-c2564541336c.jpg)

B) Comment va-t-on pouvoir concrètement gérer la plateforme ? En effet c'est la personne de l'accueil qui la gérera. Quel sera son accès dessus ? Comment y accèdera-t-il ?

C) Est-il possible de relier cette plateforme avec son adresse email accueil@artetmarges.be pour l'accès, les emails de confirmation et rappel ? 

D) Pour valider la réservation, comment cela se passe-t-il ? Doit-il les valider une part une ? Recevera-t-il des notifications par email ou il faudra qu'il check la plateforme ? 

On peut s'appeler demain si c'est plus pratique pour toi !

**Comment by pacomski** [comment]
A) Oui, je fais ça dès que le module est terminé
B) Vous allez avoir un accès (c'est un module à part du site) user + mot de passe
C) Oui, je m'occupe de ça
D) On peut définir que les réservations sont validées par défaut, ou les valider à la main une à une. Je propose de commencer avec une validation automatique et de voir si c'est bien ou non. Dites moi votre préférence. 
E) Pour les notifications, je pense que le mail de contact est prévenus, mais je dois vérifier. En tous les cas, la gestion de tout ceci se fera sur la plateforme en question.

**Comment by FredericOszczak** [comment]
Top merci pour tes réponses !

D) Le fait est que l'on a parfois des groupes/ateliers/visites guidées qui seront réservés par un autre canal. Sur ces créneaux il faut faire attention dans les validations de réservation à ne pas dépasser la jauge de 25 personnes dans l'espace. Est-ce qu'il serait possible que la personne en charge de la plateforme puisse adapter la jauge par créneau en fonction du nombre de places restantes ?

**Comment by pacomski** [comment]
oui, c'est l'idée, mais le mieux pour ces question plutôt liées à l'admin de ce module est maintenant de voir en direct avec Fred, dont je vous ai envoyé le contact par mail.
