### ISSUE TITLE
Boutons réservations 

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1065]
Hello Pacôme, 

La plateforme est déjà utilisée c'est top ! 

- Est- il possible d'ajouter un bouton dans EXPOSITIONS ACTUELLE au dessus du dossier de presse ? 
- Est-il aussi possible dans la fenêtre POP UP spéciale COVID d'enlever les informations concernant la réservation par l'adresse email et de mettre un bouton ?

Merci :)

**Comment by pacomski** [comment]
c'est fait !
