### ISSUE TITLE
QR vidéo

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1078]
Hello Pacôme ! 

Voici les vidéos à linker. Une par page et un QR correspondant à chaque ! Dis moi si quelque chose pose problème.

Merci ! Belle journée ! 

https://youtu.be/KEx_e8ss8q8
https://youtu.be/4GL-8SdgFzc
https://youtu.be/_x-aKlCvubg
https://youtu.be/j6cik9t8z2s
https://youtu.be/QPAPcBraMkM
https://youtu.be/5VBnLlI6fvQ
https://youtu.be/Ywsr-9AMi00
https://youtu.be/fNIoII1CJFs
https://youtu.be/63iYeVjNmBI

**Comment by pacomski** [comment]
Bonjour, normalement c'est bon !
