### ISSUE TITLE
Pas d'email de confirmation NL

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1079]
Hello Pacome, 

Plusieurs visiteu.r.se.s néerlandophones nous indiquent qu'ils ne reçoivent pas d'emails de confirmation suite à leur réservation sur la plateforme, peux-tu vérifier ce qu'il se passe s'il te plait ? 

Merci ! Belle après-midi !

**Comment by pacomski** [comment]
Est-ce que tu peux me confirmer qu'il n'ont rien dans leur spams ? 
Et aussi, avez vous testé de votre côté ?

Pour ma part tout semble ok, j'ai reçu un mail dans la minute avec ceci : 

![confirm-AM-NL](https://user-images.githubusercontent.com/1880537/107067009-f96cf480-67de-11eb-9266-08f31aa4de65.png)

**Comment by FredericOszczak** [comment]
Hello ! 

Merci ! Si ça se reproduit on demandera aux personnes d'aller vérifier leurs spams...
