### ISSUE TITLE
Ajout tranches horaires plateforme résa

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1080]
Hello ! 

Serait-il possible d'ajouter les horaires suivants à la plateforme de résa dans les trois langues s'il te plait ?
11h30
12h30
13h30
14h30
15h30
16h30

On se rend compte qu'autrement les gens arrivent tous à l'heure fixe et sont super nombreux en même temps dans notre petite accueil... zéro niveau covid safe !

**Comment by pacomski** [comment]
Hello, c'est Fred de Tactic/Domaine Public qui à la main sur l'appli de reservation. 
Est ce que tu peux voir avec lui directement ? 

Si ok, tu peux clôturer l'issue dans la foulée ;)

**Comment by FredericOszczak** [comment]
Ok !
