### ISSUE TITLE
Ajout biographies artistes

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1081]
Hello Nina ! J'espère que tu vas bien ! 

J'ai mis à jour les biographies dans les trois langues de Carol bailly, Dominique Bottemanne, Martine Copenaut, David Houis, RaphaËl Michel et Antoine Mvumbi. 

J'espère que j'ai tout bien fait avec les listes... Je les ai mises là, j'espère aussi que c'est le bon endroit ! https://github.com/communicationartetmarges/art-et-marges
N'hésites pas si je me suis trompée quelque part !

**Comment by ninwille** [comment]
Hello, c'est bien le bon endroit, par contre j'ai un petit soucis de compatibilité... 
Est-ce que lorsque tu as modifié le fichier tu avais bien un élément par colonne (PRENOM/NOM/DATES/IMAGE/BIOGRAPHIE)?

**Comment by FredericOszczak** [comment]
Non, tout était dans une seule colonne !

**Comment by ninwille** [comment]
Ok, c'est pour ça, j'imagine que quand tu l'as enregistré ça s'est formaté comme ça. 
Est-ce que le programme avec lequel tu l'as ouvert t'as demandé comment faire la séparation? (avec Libre Office c'est demandé en tout cas). Si oui, la prochaine fois il faut lui dire de séparer avec les virgules (et les point-virgules je pense), pour que chaque élément soit bien dans une colonne séparée. Pour cette fois-ci je vais me débrouiller avec ça, vu qu'il n'y a que 6 artistes à modifier.

**Comment by FredericOszczak** [comment]
Ok j'essaierai de l'ouvrir avec Libre Office ! 
Merci beaucoup :)
