### ISSUE TITLE
URGENT Problème site web

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1087]
![Screenshot_2021-03-04-09-50-51-165_com android chrome](https://user-images.githubusercontent.com/22938933/109946051-1f02f600-7cd8-11eb-95c4-31fa58b5f992.jpg)

Bonjour ! 

Nous avons un problème avec le site web sur plusieurs moteurs de recherche. Il ne s'affiche plus pour problème de sécurité. C'est très embêtant car les visiteu.r.se.s ne peuvent plus réserver leur visite ni voir toutes nos activités. Il est de même indiqué que le certificat de sécurité du site expire le 3 mars ? 
Savez-vous comment régler ce problème ? 
Merci pour votre aide :)

**Comment by pacomski** [comment]
hello, oui, c'est réglé ;)

**Comment by FredericOszczak** [comment]
Top merci beaucoup !
