### ISSUE TITLE
Problème https://www.artetmarges.be/fr/index.html 

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1149]
Actuellement, sur le moteur de recherche Chrome, les modifications d'images pour l'exposition A VENIR CHANSON D'AMOUR n'ont pas fonctionnées. 
A voir suite aux changements :) 

Bien à vous ! Merci !

**Comment by ninwille** [comment]
Le problème existe-t-il encore?

**Comment by FredericOszczak** [comment]
C'est tout bon ! Merci !
