### ISSUE TITLE
Modif logo 

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1168]
Est-ce possible de mettre ce logo partout, même sur la plateforme de réservation ? Merci ! 
![rose avatars-web-eps-01](https://user-images.githubusercontent.com/22938933/116256600-a0748300-a773-11eb-882c-894c5462d32e.png)

**Comment by ninwille** [comment]
@pacomski : je le change sur le site, est-ce que je peux te laisser gérer la plateforme de réservation?

**Comment by pacomski** [comment]
Ca me semble déjà tout bon partout.. 
@FredericOszczak tu peux me confirmer ? 
Et fermer l'issue si c'est bien ok ? :)

**Comment by pacomski** [comment]
( @FredericOszczak tu peux aussi changer de nom si tu veux) ;)

**Comment by FredericOszczak** [comment]
Sur Chrome sur PC je ne vois pas la modif sur la plateforme de réservation !

Ahah j'aime beaucoup m'appeler FredericOszczak x)

**Comment by FredericOszczak** [comment]
Merci bcp pour tous les changements hyper rapides que vous avez fait :)

**Comment by pacomski** [comment]
j'ai l'impression que ce serait une question de cache : essaye de recharger la page en vidant le cache en même temps (shift+ctrl+R)

**Comment by FredericOszczak** [comment]
Yes ça a fonctionné ! 
merci pour la technique ! 
En revanche sur la plateforme de réservation le logo s'affiche aussi sur cette page : 
![Capture d’écran 2021-05-01 111536](https://user-images.githubusercontent.com/22938933/116777788-9520a080-aa6e-11eb-82c7-0897f2718544.jpg)


Est-ce possible de le changer ? Merci :)

**Comment by pacomski** [comment]
Hello, oui, bien vu, c'est du côté de Domaine Public.
Je leur forward ça.

**Comment by pacomski** [comment]
c'est bon

**Comment by FredericOszczak** [comment]
Top merci beaucoup ! Belle semaine :)
