### ISSUE TITLE
Problème avec les pages activités

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1175]
Hey Nina ! 

Merci pour ces mises à jour !

Je me rends compte que les activités ne sont pas mises dans l'ordre chronologique. Je ne savais pas trop dans quel sens encoder les issues pour qu'elles le soient ? Dis moi pour la prochaine fois.

Est-ce possible de le changer ? Dans l'ordre inverse d'actuellement du coup ? Le vernissage en premier ! 

Merci !

**Comment by ninwille** [comment]
Hello, oui pas de soucis, je fais ça tout de suite! 
Je commence toujours par les premières encodées normalement (de bas en haut dans les issues), mais il est possible que je me sois trompée ;)

**Comment by FredericOszczak** [comment]
Top merci beaucoup ! 
Donc attend, ça veut dire que celle que j'encode en premier, tu les encodes aussi en premier sur le site donc elles seront en bas de la page ?

**Comment by ninwille** [comment]
non j'encode de haut en bas, donc ce que tu encodes en premier apparaitra en haut sur le site!

**Comment by FredericOszczak** [comment]
Ok ! Good to know ;) 

Merci beaucoup d'avoir fait tous ces changements super rapidement !
