### ISSUE TITLE
URGENT Certificat expiré Firefox

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1187]
Hello ! 
On nous signal que le site ne s'affiche pas sur Firefox pour un soucis de certificat... il me semble que ça avait fait ça il y a quelques mois donc ça doit vous évoquer pus de chose qu'à moi ;) 

Merci pour votre aide !

**Comment by FredericOszczak** [comment]
Ca fait cela sur tous les navigateurs en fait !

**Comment by ninwille** [comment]
Hello, normalement c'est réglé!
