### ISSUE TITLE
MODIF https://www.artetmarges.be/collection/fr/martha-grunenwaldt.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1203]
Changer l'image par : 
![Martha, GRUNENWALDT](https://user-images.githubusercontent.com/22938933/120805217-d0b6fa80-c545-11eb-858b-7688de55fd66.jpg)

**Comment by ninwille** [comment]
Hello, je fais ça! 
Pour les images, c'est une même image qui est utilisée dans les 3 langues, donc pas besoin de 3 issues pour la changer, une suffit!
Bon w-e!
