### ISSUE TITLE
MODIF https://www.artetmarges.be/fr/activ.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1208]
Modifier l'article ROUTOURNETOURNE !

Modifier à partir de infos, copier-coller : 

Infos : de 17h à 18h les 11.06 - 09.07 - 20.08 - 10.09.2021
Sur réservation via accueil@artetmarges.be - tous publics - GRATUIT

Remplacer l'image par celle-ci : 
![RoutourneTourne Visuel](https://user-images.githubusercontent.com/22938933/121207259-71285a00-c879-11eb-83b1-9ca3af5480fc.jpg)

Merci :)

**Comment by FredericOszczak** [comment]
Hello ! L'image a-t-elle bien  été changé et c'est un bug d'affichage de mon navigateur comme la dernière fois ?

**Comment by ninwille** [comment]
Hello, as-tu essayé le fameux ctrl+maj+r (recharger complètement la page)? Il s'agit sans doute d'un soucis de cache (le navigateur garde les anciennes infos en mémoire car le nom de l'image est le même), car chez moi l'image est bien adaptée. Par la suite je changerai le nom de l'image pour le navigateur arrête de s'y tromper :)

**Comment by FredericOszczak** [comment]
Hey ! 

Du coup ça n'a toujours pas changée malgré le fameux ctrl+maj+r ;) Possible de faire quelque chose ?

**Comment by pacomski** [comment]
est ce que c'est toujours le cas ? 
chez moi ça semble ok.. 
si c'est ok tu peux fermer l'issue @FredericOszczak ;)

**Comment by FredericOszczak** [comment]
Malheureusement toujours pas... !

**Comment by ninwille** [comment]
Hello, bien vu! 
Je me demande si on a pas confondu avec l'image précédente, oups! En tout cas cette fois-ci c'est envoyé, il faut juste un petit temps (environ 10-15m) pour que ça soit mis en ligne et enfin réglé!
