### ISSUE TITLE
changement de LOGO

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1268]
est-ce possible de changer le logo partout sur le site et sur la plateforme de réservation pour le 28.09 matin ?
![AVATAR GAPHISTES](https://user-images.githubusercontent.com/22938933/134690104-b18c1d9f-03c1-4b52-8b68-3aee7d12e6cc.jpg)

**Comment by ninwille** [comment]
Hello, 
Est-ce normal que l'image soit carrée (par rapport aux ronds d'avant)? Du coup ça ne se met pas bien partout:

![Screenshot from 2021-09-27 11-23-21](https://user-images.githubusercontent.com/47986775/134881968-f9db5fe8-3a8e-4a6b-97ae-b10f6e9c5fb2.png)

**Comment by FredericOszczak** [comment]
![AVATAR GAPHISTES CERCLE](https://user-images.githubusercontent.com/22938933/135122479-12cebdd8-7401-4f62-8508-717f26c26e39.png)

je l'ai rogné. Est-ce que ça fonctionne cette fois ?

**Comment by ninwille** [comment]
oui, je pense que c'est mieux! Je fais ça!
