### ISSUE TITLE
Page front.html et expo.html (à venir) - mise à jour FR + NL + UK

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#13]
![richard-2-web](https://cloud.githubusercontent.com/assets/22938933/22465019/f4f19310-e7b9-11e6-97a9-b761b820010f.jpg)

Pouvez-vous remplacer **sur la page d'accueil** le contenu de "Sauver le monde ?" ? 

Visuel
Titre et dates.
Seuls & accompagnés
23/06-17/09/2017

Sur la page expo.htm, dans les expos à venir ajouter ceci après l'expo Mesmer : 
Seuls & accompagnés
23/06-17/09/2017
VISUEL
Les œuvres de cette exposition n’auraient sans doute pas vu le jour, ou du moins pas sous ces formes-là, sans l’environnement qui a présidé à leur création,  celui d’un atelier collectif institutionnel ou d’un compagnonnage privé. Elles sont chacune fruit de rencontres, entre une personne en défaut d’autonomie sociale ou mentale et un animateur d’atelier, artiste, complice. Parfois plusieurs.

Dans quelle mesure ces accompagnements artistiques, psychologiques et pédagogiques divers peuvent-ils être catalyseurs d’expressions si substantiellement individuelles ?
L’exposition  “seuls & accompagnés” lie plaisir esthétique à réflexion, intelligence et … vigilance.

Avec les œuvres de: Sylvain Cosijns, Philippe da Fonseca, Véronique Declercq, 
Richard Moszkowicz, Pascal Tasini

Conception : Gérard Preszow/ Assistante : Magalie Thiaude

Les versions NL eu UK suivront :) Merci !

**Comment by FredericOszczak** [comment]
Version NL 

Alleen & begeleid
23/06-17/09/2017
De werken van deze tentoonstelling zouden waarschijnlijk nooit gemaakt zijn, of toch niet in deze vorm, buiten de omgeving waarin ze tot stand kwamen, meer bepaald in het kader van het groepsatelier van een instelling of een individuele begeleiding. Elk van hen is het resultaat van een ontmoeting tussen een persoon zonder sociale of mentale autonomie en een atelierverantwoordelijke, kunstenaar of bondgenoot. Soms meerdere. 

In welke mate kan die artistieke, psychologische en pedagogische begeleiding de katalysator zijn van dergelijke werken, die per definitie zo intens individueel zijn ? 
De tentoonstelling “alleen en begeleid » verbindt esthetisch genot met beschouwing, intelligentie en… waakzaamheid .

Met de werken van : Sylvain Cosijns, Philippe da Fonseca, Véronique Declercq, 
Richard Moszkowicz, Pascal Tasini

Concept : Gérard Preszow/ Assistente : Magalie Thiaude

**Comment by FredericOszczak** [comment]
UK

Alone & accompanied
23/06/2017 – 17/09/2017

The works of this exhibition would undoubtedly never have seen the light of day, at least not in that form, without the setting in which they were created: an institutional collective studio or private mentoring. Each of them is the outcome of encounters, between a person with a mental or autonomy defect, and a studio supervisor, artist or accomplice – sometimes many of them together.

To what extent can artistic, psychological and educational mentoring be a catalyst for such substantially individual forms of expression?

The exhibition “alone and accompanied” combines aesthetic pleasure with reflection, intelligence and… vigilance.

With works from : Sylvain Cosijns, Philippe da Fonseca, Véronique Declercq, 
Richard Moszkowicz, Pascal Tasini

Concept : Gérard Preszow/ Assistant : Magalie Thiaude

**Comment by FredericOszczak** [comment]
UK

Alone & accompanied
23/06/2017 – 17/09/2017

The works of this exhibition would undoubtedly never have seen the light of day, at least not in that form, without the setting in which they were created: an institutional collective studio or private mentoring. Each of them is the outcome of encounters, between a person with a mental or autonomy defect, and a studio supervisor, artist or accomplice – sometimes many of them together.

To what extent can artistic, psychological and educational mentoring be a catalyst for such substantially individual forms of expression?

The exhibition “alone and accompanied” combines aesthetic pleasure with reflection, intelligence and… vigilance.

With works from : Sylvain Cosijns, Philippe da Fonseca, Véronique Declercq, 
Richard Moszkowicz, Pascal Tasini

Concept : Gérard Preszow/ Assistant : Magalie Thiaude

**Comment by pacomski** [comment]
trop de choses pour une seule issue : 
- à faire sur front.html fr-nl-en = 1 issue
- à faire sur expo.html fr-nl-en = 1 autre issue
