### ISSUE TITLE
ajout d'article sur https://www.artetmarges.be/fr/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1328]
_au dessus de la rubrique Á VENIR, ajouter une rubrique :_ 

### EXTRA-MUROS

_et dans celle-ci, afficher l'article suivant :_ 

![image Juanma site web](https://user-images.githubusercontent.com/22938933/140361419-7ab48f77-2922-46b8-8b83-c0a7ff760c2f.jpg)
Juanma Gonzalez, © Coll. Art et marges musée

**LE ART ET MARGES MUSEE A LA VITRINA DE VALONIA (LA HAVANE)**
**09.11-06.12.2021**

Le ART ET MARGES MUSEE emmène ses plus belles sandales pour une exposition d’un mois à Cuba. Les semelles peintes de l’artiste-cordonnier Juanma Gonzalez sont accompagnées de quelques autres pièces remarquables de la collection par Umberto Bergamaschi, Philippe Condylis, Sylvain Cosijns, Antonio Dalla Valle, Serge Delaunay, Paul Duhem, Martha Grünenwaldt, Jeroen Hollander, Alexis Lippstreu, André Prues, Kenneth Rasmussen, Fernanda Reyns, Daniel Sterckx, Pascale Vincke et Lenka Zelenovic.

Un projet soutenu par la Région Bruxelles-Capitale et l’Ambassade de Belgique à Cuba. 

![Logo_RBC](https://user-images.githubusercontent.com/22938933/140378583-91d259a6-64dc-40b2-a215-353a5bd4eacf.jpg)

![logo ambassade](https://user-images.githubusercontent.com/22938933/140378595-1e7f4e4b-ae41-4fee-a574-fd828c2e2f63.png)

_si possible, mettre les logos sur la même ligne_

**Comment by ninwille** [comment]
Hello, j'ai ajouté l'expo, mais je vois que les logos ne s'affichent pas bien. Je les ai retiré le temps de faire ça bien, cela sera fait d'ici mardi!
