### ISSUE TITLE
ajout sur la page https://www.artetmarges.be/nl/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1329]
_au dessus de la rubrique TOEKOMSTIGE TENTOONSTELLING, ajouter une rubrique :_

### EXTRA-MUROS

_et dans celle-ci, afficher l'article suivant :_

![image Juanma site web](https://user-images.githubusercontent.com/22938933/140379480-97859273-5b70-40b0-96a3-8b02a303c786.jpg)
Juanma Gonzalez, © Coll. Art et marges museum

### HET ART ET MARGES MUSEUM IN VITRINA DE VALONIA (HAVANA)

Het ART ET MARGES MUSEUM neemt zijn mooiste sandalen mee naar Cuba voor een tentoonstelling van één maand. De beschilderde zolen van de kunstenaar-schoenmaker Juanma Gonzalez worden vergezeld door enkele andere opmerkelijke stukken uit de collectie van Umberto Bergamaschi, Philippe Condylis, Sylvain Cosijns, Antonio Dalla Valle, Serge Delaunay, Paul Duhem, Martha Grünenwaldt, Jeroen Hollander, Alexis Lippstreu, André Prues, Kenneth Rasmussen, Fernanda Reyns, Daniel Sterckx, Pascale Vincke en Lenka Zelenovic.

Een project gesteund door het Brussels Hoofdstedelijk Gewest en de Belgische Ambassade in Cuba.

![Brussels hoofdstedelijk gewest](https://user-images.githubusercontent.com/22938933/140379417-989c69fb-5735-40ca-9984-36e64461b53a.png) 
![logo ambassade](https://user-images.githubusercontent.com/22938933/140380123-ba7adcdf-76ce-4ee1-8f92-ffbd07bddd7a.png)

_si possible, mettre les logos sur la même ligne_

**Comment by pacomski** [comment]
@FredericOszczak  j'ai mis le même logo bilingue partout, c'est plus rapide, si ça ne va pas dites moi.


Sinon si c'est ok vous pouvez fermer cette issue.
