### ISSUE TITLE
ajout d'article sur https://www.artetmarges.be/en/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1330]
_au dessus de la rubrique UPCOMING, ajouter une rubrique :_

### EXTRA-MUROS

_et dans celle-ci, afficher l'article suivant :_

![image Juanma site web](https://user-images.githubusercontent.com/22938933/140380513-fd5ff271-820c-4c83-855c-1b8e951a106c.jpg)
Juanma Gonzalez, © Coll. Art et marges musée

### 11.09-12.06.2021

The ART AND MARGES MUSEUM takes its most beautiful sandals for a month-long exhibition in Cuba. The painted soles of the artist-cobbler Juanma Gonzalez are accompanied by some other remarkable pieces from the collection by Umberto Bergamaschi, Philippe Condylis, Sylvain Cosijns, Antonio Dalla Valle, Serge Delaunay, Paul Duhem, Martha Grünenwaldt, Jeroen Hollander, Alexis Lippstreu, André Prues, Kenneth Rasmussen, Fernanda Reyns, Daniel Sterckx, Pascale Vincke and Lenka Zelenovic.

A project supported by the Brussels-Capital Region and the Belgian Embassy in Cuba.
![région de bruxelles capitale](https://user-images.githubusercontent.com/22938933/140380736-5d89e956-cd55-4a4a-8159-71f92374c953.jpg)
![logo ambassade](https://user-images.githubusercontent.com/22938933/140380745-3236e50b-7f48-4a6f-9442-6a7a572241eb.png)

_si possible, mettre les logos sur la même ligne_

**Comment by pacomski** [comment]
@FredericOszczak j'ai mis le même logo bilingue partout, c'est plus rapide, si ça ne va pas dites moi.

Sinon si c'est ok vous pouvez fermer cette issue.
