### ISSUE TITLE
meilleur intégration modifs Serge D. dans le script de genération de la collection

### ISSUE THREAD

**Issue by pacomski** [communicationartetmarges/art-et-marges#1370]
les modifications des issues #1369  #1368 #1367 ont été faite directement sur le html généré. 
A intégrer plus correctement dans le script de génération de la collection

**Comment by ninwille** [comment]
Voilà, c'est modifié dans les fichiers 'collection-all-fr', 'collection-all-nl' et 'collection-all-fr' afin que cela soit pris en compte lors de la génération automatique (que je n'ai pas lancé vu que ça n'est pas nécéssaire cette fois-ci).
