### ISSUE TITLE
Nouveau logo de la ville de Bruxelles dans le footer

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#14]
La ville de Bruxelles a changé de logo (sont hyper tatillons avec ça). 
![bxl_logo_horiz_filet_fr_nl](https://cloud.githubusercontent.com/assets/22938933/22469988/1782464a-e7ce-11e6-9807-196933d3cde2.png)

Voici le nouveau à insérer dans le footer (FR / NL / UK).

Merci.

**Comment by pacomski** [comment]
ok
