### ISSUE TITLE
A FAIRE LE 13.06 : suppression d’article sur https://www.artetmarges.be/en/activ.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1504]
Supprimer l’article PRINTMAKING FOR ALL

**Comment by pacomski** [comment]
Hello @FredericOszczak , est ce que c'est bien cet article qu'il faut supprimer ?

Pas plutôt la visite guidée ?

**Comment by FredericOszczak** [comment]
oui, effeectivement ! C'est bien la visite guidée. Je me suis plantée. Merci
Sarah
