### ISSUE TITLE
A FAIRE LE 22.08 TOUT PILE | remplacement du logo partout sur le site 

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1530]
Attention : ne pas oublier le logo dans l’onglet de navigation ni celui quand on navigue dans les fiches d’artistes (le musée/la collection) et sur toutes les pages de la plate-forme de réservation. 

![avatar carré](https://user-images.githubusercontent.com/22938933/186119904-ad098b99-5516-4e46-b19c-6addb62629dd.jpg)

**Comment by pacomski** [comment]
Hello ! Ce logo est en .jpg avec un fond blanc carré. 
Est ce que c'est bien comme ça que vous le voulez ? 

![image](https://user-images.githubusercontent.com/1880537/186134823-a0e76f63-8f6a-4e0f-802e-f575f32b4367.png)

**Comment by pacomski** [comment]
si pas il me le faudrait en .png avec un fond transparent là où il faut.

**Comment by FredericOszczak** [comment]
![avatar rond transparence](https://user-images.githubusercontent.com/22938933/186142563-8d2bbaec-a8b6-440a-b2b7-b8cb30e24657.png)

**Comment by FredericOszczak** [comment]
![avatar rond transparence](https://user-images.githubusercontent.com/22938933/186142807-e179e946-313e-4524-ac5b-1c40ea22b2a0.png)

**Comment by pacomski** [comment]
ok, merci !
