### ISSUE TITLE
Renouvellement documents en lien sur https://www.artetmarges.be/fr/activ.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1532]
On renouvelle les tarifs, il faut donc remplacer les documents en lien (Plus d’informations) sous chacun de ces titres : 

ADULTES ET ENSEIGNEMENT SUPÉRIEUR
[ADULTES & SUP FR_WEB.pdf](https://github.com/communicationartetmarges/art-et-marges/files/9463064/ADULTES.SUP.FR_WEB.pdf)

ENFANTS ET ADOS
[KIDS & ADO FR_WEB.pdf](https://github.com/communicationartetmarges/art-et-marges/files/9463120/KIDS.ADO.FR_WEB.pdf)

L’ANNIVERSAIRE DE VOTRE ENFANT AU MUSÉE
[Uploading Anniversaire FR.pdf…]()

**Comment by pacomski** [comment]
hello @FredericOszczak 
le fichier pour les anniversaire n'est pas passé on dirait

**Comment by pacomski** [comment]
les autres sont mis à jour
