### ISSUE TITLE
A FAIRE LE 14.11.2022 PILE : remplacement du logo partout sur le site

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1582]
(ne pas oublier les pages relatives aux artistes dans https://www.artetmarges.be/collection + le logo dans la barre de navigation + celui sur la plate-forme de réservation)

**Comment by pacomski** [comment]
hello @FredericOszczak  ! 

c'est quel logo qu'il faut mettre ?

**Comment by FredericOszczak** [comment]
Sorry,

C'est celui-ci


SarahCommunication - Communicatie

Art et marges musée - museum
Rue Haute 314 – Hoogstraat 314
1000 Bruxelles - Brussel
Tél : 32 (0)2 533 94 90
artetmarges.be <http://www.artetmarges.be/>
Instagram <https://www.instagram.com/art_et_marges_musee_museum/>
Facebook <https://www.facebook.com/artetmarges/>

**Comment by FredericOszczak** [comment]
![logo couleurs photo brut](https://user-images.githubusercontent.com/22938933/201958292-9209ac0a-65ac-46cc-afa0-543979453e39.png)
 voici, désolée, j'avais oublié de le joindre
