### ISSUE TITLE
Lien RÉSERVATION VISITE dans la barre de menu (dans les 3 langues)

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1583]
Serait-il possible de faire en sorte qu’il apparaisse sous le même format que les autres liens de la barre de menu ? En l’état, avec le surlignage, on a l’impression que ça nous indique la page sur laquelle on se trouve, ça crée une confusion.

**Comment by pacomski** [comment]
c'est fait
