### ISSUE TITLE
Vignette video Youtube page d'accueil

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#17]
A la demande de Tatiana, j'ai modifié la vignette de la vidéo "La Chanterelle, oiseaux de passage" sur youtube.

Sur notre chaîne c'est ok. Mais elle n'apparaît pas sur la page d'accueil du site internet. Vous pouvez faire quelque chose ?

**Comment by pacomski** [comment]
de mon coté ça a changé.
As tu essayé de recharger ta page en vidant le cache du navigateur ?
