### ISSUE TITLE
A FAIRE LE 29.05 Modification sur https://www.artetmarges.be/fr/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1711]
Faire passer l’article HORS CADRES dans PRECEDEMMENT

**Comment by pacomski** [comment]
Hello @FredericOszczak, est-ce qu'on fait ça maintenant ?

**Comment by FredericOszczak** [comment]
oups, non, à faire le 29.05. Je modifie l'intitulé. Bien vu !
