### ISSUE TITLE
Ajout d’article sur https://artetmarges.be/nl/activ.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#1791]
_A la suite de DIA DE MUERTOS | WORKSHOP MAGISCHE BANNERS_ :  
![newsletter-2](https://github.com/communicationartetmarges/art-et-marges/assets/22938933/ded16440-5254-4d2a-a2f8-2e3e747aa460)

### DONDERDAG 9 NOVEMBER 17H30

L'Haha is een papieren tijdschrift dat jaarlijks een overzicht publiceert van een zeer atypische plaats in zijn context. Sinds een aantal jaren voert het een intermitterend en rondtrekkend werk uit van inventarisatie, veldwerk en archivering, gericht op het identificeren en documenteren van verschillende vormen van geografische en architecturale apax.

Het eerste nummer volgt in de voetsporen van een krot dat zo'n veertig jaar geleden werd verwoest en dat ooit de woning was van Jean Smilowski, de Robinson van het oude Lille, zoals hij bekend stond bij zijn 'ontdekkers'...

In samenwerking met ISELP | In het Frans | met reservatie: [info@artetmarges.be](mailto:info@artetmarges.be)

**Comment by ninwille** [comment]
Hello !  est-ce normal que ça ne soit pas le même mail en fr et nl?
