### ISSUE TITLE
Ajustement page 'Musée' - FR/NL/EN

### ISSUE THREAD

**Issue by pacomski** [communicationartetmarges/art-et-marges#1981]
On a ainsi un peu réfléchi à réorganiser la page "Musée" de notre site.
Dans l'idéal, on voudrait modifier la répartition comme suit : 

colonne de gauche : 

PRÉSENTATION
on garde le texte qui va de "Situé" à "même"

PUBLICATION
on fait glisser tout ce que contient la rubrique publication dans cette colonne

HISTORIQUE
qui reprend toutes les photos et les dates actuellement présentes dans la colonne de gauche

--------

Colonne de droite : 

COLLECTION
avec tout ce que contient actuellement cette rubrique

**Comment by pacomski** [comment]
@sarahkokot / @FredericOszczak : je viens de faire les modifications, dans les trois langue, c'est en ligne. 
Est-ce que tout est ok  ?

**Comment by FredericOszczak** [comment]
oui, merci beaucoup !
