### ISSUE TITLE
[Activité] : Accessibilité - colonne de droite trop foncée.

### ISSUE THREAD

**Issue by pacomski** [communicationartetmarges/art-et-marges#1984]
Sur la page https://www.artetmarges.be/fr/activ.html la colonne de droite est trop foncée, il n'y a pas assez de contraste pour que ce soit lisible pour les personnes mal-voyantes (qui sont en plus visées en tête de colonne).

@sarahkokot ou @vvvvcccc : fournir la référence de la couleur à utiliser (fond et/ou texte)

**Comment by FredericOszczak** [comment]
Passer le texte en blanc. 
Sarah

**Comment by pacomski** [comment]
ok
