### ISSUE TITLE
Ajout sur https://www.artetmarges.be/nl/activ.html à la suite de l’article BEZOEK IN AANWEZIGHEID VAN DE KUNSTENAAR MICHEL GOYON (in het FR)

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#2063]
![DSC_0301-2](https://github.com/user-attachments/assets/dcd75b13-4ed3-420b-a0df-1e90aa1fa57b)
### DIMANCHE 1er DÉCEMBRE 14:00-15:30

Qui dit premier dimanche du mois, dis gratuité au Art et marges musée ! Et en ce premier dimanche du mois de décembre, on vous gâte de plus belle avec une visite guidée complètement gratuite dans l’exposition fascinante de Michel Goyon : ARBORESCENCES. 

Réservation nécessaire ! : accueil@artetmarges.be

**Comment by pacomski** [comment]
Hello @FredericOszczak 

il manque la traduction nl on dirait ;)

**Comment by pacomski** [comment]
ha non, elle est après si j'ai bien vu
