### ISSUE TITLE
Gros problème d'affichage page activ.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#23]
Tatiana a un gros problème d'affichage sur son écran (voir printsceeen ci-joint). Sur le mien tout est ok. Sur ma tablette aussi. Elle a un écran 4/3, moi un 16/9. Je ne sais pas si ça joue un rôle ?

Entre les activités il y a un espace démesuré.

Sur mon écran, entre "29.04.2017 10h30 - 12h" et "Tous les derniers samedis du mois etc" je vois un tout petit carré blanc avec un fin liseré gris. Une balise au mauvais endroit ?

Ce petit carré blanc apparaît partout où les espaces sont démesurés.

![espaces site](https://cloud.githubusercontent.com/assets/22938933/22653435/a2119e7c-ec89-11e6-84b0-63926176d2f5.png)

**Comment by FredericOszczak** [comment]
Sur mon écran, entre "29.04.2017 10h30 - 12h" et "Tous les derniers samedis du mois etc" je vois un tout petit carré blanc avec un fin liseré gris. Une balise au mauvais endroit ?

Ce petit carré blanc apparaît partout où les espaces sont démesurés.

**Comment by pacomski** [comment]
Il me faudrait des informations sur la version de windows, et la version d'internet explorer utilisée. 
Pour info Internet Explorer est abandonné par Microsoft depuis 2015, pour un navigateur à jour privilégiez Edge -la suite de IE- , Chrome ou Firefox.

**Comment by pacomski** [comment]
ca devrait être ok maintenant.
