### ISSUE TITLE
Page activ.html FR : modifications dans le texte et photos à insérer

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#27]
Matinée créative
25.02.2017 10h30 - 12h
25.03.2017 10h30 - 12h
29.04.2017 10h30 - 12h

Tous les derniers samedis du mois, le art et marges musée propose aux enfants des activités créatives et ludiques au départ de l’exposition Gustav Mesmer LIEN HYPERTEXTE **http://artetmarges.be/fr/expo.html**. Au programme : observer, découper, écouter, coller, assembler, choisir, jouer, échanger… découvrir ensemble ! (une activité différente chaque fois)
Sur réservation.
Pour enfants de 6 à 12 ans
4€ par enfant.
Gratuit pour les enfants du quartier.
Inscription 02/533 94 90 - info@artetmarges.be

Museum Night Fever
11.03.2017
19:00-01:00 du matin 

**Gustav Mesmer, né en 1903 et décédé en 1994, n’a presque rien connu du XXe siècle. 
Interné en hôpital psychiatrique dans la vallée du Lautertal dès l’âge de 26 ans, Mesmer s’est concentré sur sa mission obsédante : créer des machines volantes qui lui offriraient la liberté. 

Cette nuit du 11 mars 2017, prolongez le rêve de Mesmer en créant votre propre flotte d’engins volants au rythme d’une ambiance électro et expérimentale. 

Atelier participatif :
Tout au long de la soirée, le collectif 1soir vous proposera de créer vos engins volants qui complèteront une installation évolutive.**

Concerts : 
19h15 Eric Kinny
20h00 **Donatien Tomandini**
20h45 **Donatien Tomandini**
 21h30 Kirsten Danst
22h15 Kirsten Danst
23h00 Real Trvth
23h45 Real Trvth
00h30 Eric Kinny
En partenariat avec Le Créahm-Bruxelles, atelier musique
www.museumnightfever.be * 23 musées * Bruxelles * 15€ /11€ (prévente) + 7€ avec afterparty 

Activité en famille en partenariat avec Le Wolf (FR)
samedi 18.03.2017 + samedi 20.05.2017
14:00-17:00

Table-ronde dans le cadre du festival What is it? - Alice Gallery
30.03.2017
Participation du art et marges musée à la table-ronde du festival What is it? autour de l’art brut numérique.

Fête de la gratuité
02.04.2017

Visite guidée dans le cadre du Erfgoeddag
23.04.2017
14:00
La journée du patrimoine organisée par la Vlaamse Gemeenschapscommissie a cette année « le soin » pour thème. 
…L’art comme soin… Comment cela se traduit-il dans les œuvres de la collection du art et marges musée ? Nous posons la question dans une visite guidée, sur les traces des artistes qui créent en dehors du circuit artistique habituel. Une découverte de l’art outsider.
Sur réservation : 02 533 94 90 - info@artetmarges.be
Entrée et visite guidée gratuite pour les personnes inscrites

**ENLEVER LE TEXTE EN NEERLANDAIS !!!!! …Kunst als zorg… Hoe vertaalt zich dit in de kunstwerken van de collectie van het art & marges museum ? Wij stellen deze vraag tijdens een geleid bezoek, in het spoor van de kunstenaars die buiten het officiële artistieke circuit creëren. Een ontdekking van outsider kunst.**

Visites guidées expo Gustav Mesmer LIEN HYPERTEXTE**http://artetmarges.be/fr/expo.html** (art et marges musée) + Een andere wereld LIEN HYPERTEXTE**http://www.museumdrguislain.be/fr/tentoonstellingen/Details/9050/un-autre-monde** (Musée du dr. Guislain, Gand)
(une activité des Amis du art et marges musée)
07.05.2017
Le musée du dr. Guislain et le art et marges musée ont pour point commun de présenter une collection d’art outsider. En ce printemps 2017, ils ont un point commun de plus : ils accueillent des œuvres de l’artiste Gustav Mesmer dans leur exposition temporaire. Nous vous proposons de découvrir l’exposition Gustav Mesmer au art et marges musée, et de prolonger notre découverte de cet artiste à Gand, dans l’exposition « Een andere wereld ».

10:00 visite guidée au art et marges musée, expo Gustav Mesmer
12:00 co-voiturage vers Gand
13:00 pic-nic au musée du dr. Guislain 
14:00 visite guidée de l’expo « Een andere wereld » au musée du dr. Guislain

Activité réservée aux amis du art et marges musée. Devenir membre de l’association des amis du art et marges musée : amisvrienden@artetmarges.be (cotisation annuelle : 30€ cotisation individuelle/50€ cotisation familiale) 

S’inscrire : 02 533 94 94 – amisvrienden@artetmarges.be 

famille-avec-le-wolf
![activite-famille-avec-le-wolf_dsc5625_dxo](https://cloud.githubusercontent.com/assets/22938933/22656618/37e4666e-ec94-11e6-8f2b-b946fcc784a6.jpg)
erfgoeddag
![erfgoeddag_dsc5148_dxo](https://cloud.githubusercontent.com/assets/22938933/22656617/37e3f68e-ec94-11e6-9395-c9a43512248e.jpg)
matinee-creative
![matinee-creative_dsc5253_dxo](https://cloud.githubusercontent.com/assets/22938933/22656619/37e6ab7c-ec94-11e6-994a-8a85c991f688.jpg)
museum night fever 2017
![museum night fever 2017](https://cloud.githubusercontent.com/assets/22938933/22656621/37e773fe-ec94-11e6-87d2-6f699fa754d9.gif)
visite-art-et-marges-et-dr-guislain
![visite-art-et-marges-et-dr-guislain](https://cloud.githubusercontent.com/assets/22938933/22656620/37e6bc98-ec94-11e6-8bb6-a4638cecda28.jpg)

**Comment by FredericOszczak** [comment]
Remplacer le texte en NL du erfgoeddag par cette traduction : 

…Kunst als zorg… Hoe vertaalt zich dit in de kunstwerken van de collectie van het art & marges museum ? Wij stellen deze vraag tijdens een geleid bezoek, in het spoor van de kunstenaars die buiten het officiële artistieke circuit creëren. Een ontdekking van outsider kunst.

**Comment by pacomski** [comment]
merci de noter plus clairement ce qui doit être modifié (en gras ou autre) et de m'indiquer quelle image va où.

**Comment by FredericOszczak** [comment]
Les tailles de police, graisses et couleurs sont identiques à ce que tu as fait précédemment pour cette page. J'ai ajouté "TITRE :" pour chaque événement.

Les noms des images sont toutes précédées du nom de l'événement. GitHub les a-t-il renommées ?

**Comment by pacomski** [comment]
Pour les liens dans les titres : ce n'est pas le meilleur endroit pour mettre un lien, il vaut mieux privilégier les liens dans le texte.
