### ISSUE TITLE
Page activ.html NL : textes et visuels  

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#28]
Les visuels sont les mêmes que ceux de la page FR activ.html (voir issue précédente)

Creatieve morgen
25.02 + 25.03 + 29.04.2017 
10:30-12:00
Elke laatste zaterdag van de maand biedt het art et marges museum aan kinderen de mogelijkheid om de tentoonstelling Gustav Mesmer op een creatieve en speelse manier te verkennen. Op het programma staan tal van leuke activiteiten! Kijken, knippen, luisteren, plakken, knutselen, kiezen, spelen, ervaringen delen... samen ontdekken!
Met reservatie. Voor kinderen van 6 tot 12 jaar 4€ per kind. Gratis voor de kinderen van de Marollen.
Inschrijven 02/533 94 90 info@artetmarges.be

Museum Night Fever
11.03.2017
19:00-01:00 ‘s nachts 
 
**Gustav Mesmer, geboren in 1903 en gestorven in 1994, heeft bijna niets meegemaakt van de XXe eeuw. 
Geïnterneerd in een psychiatrische instelling in de vallei van Lautertal vanaf zijn 26 jaar, heeft Mesmer zich uitsluitend geconcentreerd op een obsessieve opdracht : vliegende machines ontwerpen die hem de vrijheid konden schenken. 

Deze nacht van 11 maart 2017, kan u de droom van Mesmer verlengen door zelf uw vliegende toestellen te ontwerpen op het ritme van elektro en experimentele muziek. 

Workshop :
Gedurende de ganse avond stelt het collectief 1soir u voor om uw vliegende toestellen te ontwerpen die een evolutieve installatie zullen vervolledigen.**
 
Concerten : 
19u15 Eric Kinny
20u00 **Donatien Tomandini**
20u45 **Donatien Tomandini**
 21u30 Kirsten Danst
22u15 Kirsten Danst
23u00 Real Trvth
23u45 Real Trvth
00u30 Eric Kinny
In samenwerking met Le Créahm-Bruxelles, muziekatelier
www.museumnightfever.be * 23 musées * Bruxelles * 15€ /11€ (prévente) + 7€ avec afterparty 
 
**Familie activiteit in samenwerking met Le Wolf (FR)**
zaterdag 18.03.2017 + zaterdag 20.05.2017
14:00-17:00
 
Ronde-tafel in het kader van het festival What is it? - Alice Gallery
30.03.2017
Deelname van art et marges museum aan de ronde-tafel van het festival What is it? rond numerieke art brut.
 
Fête de la gratuité
02.04.2017

Geleid bezoek in kader van Erfgoeddag
23.04.2017
14:00
De dag van het Patrimonium georganiseerd door de Vlaamse Gemeenschapscommissie heeft dit jaar « de zorg » als thema. 
…Kunst als zorg… Hoe vertaalt zich dit in de kunstwerken van de collectie van het art & marges museum ? Wij stellen deze vraag tijdens een geleid bezoek, in het spoor van de kunstenaars die buiten het officiële artistieke circuit creëren. Een ontdekking van outsider kunst.
Op reservatie : 02 533 94 90 - info@artetmarges.be
Toegang en geleid bezoek zijn gratis voor de ingeschreven personen

Geleid bezoek expo Gustav Mesmer LIEN HYPERTEXTE **http://artetmarges.be/nl/expo.html** (art & marges museum) + Een andere wereld LIEN HYPERTEXTE **http://www.museumdrguislain.be/nl/tentoonstellingen/details/9050/een-andere-wereld** (Museum dr. Guislain, Gent)
(activiteit van de vrienden van het art & marges museum)
07.05.2017
Het dr. Guislain museum en art & marges museum hebben als gemeenschappelijk punt dat ze een verzameling outsider kunst presenteren. Tijdens de lente van 2017 hebben ze er iets gemeenschappelijks bij: Ze ontvangen de kunstwerken van de kunstenaar Gustav Mesmer in hun tijdelijke tentoonstelling. Wij stellen u voor de tentoonstelling over Gustav Mesmer in het art & marges museum te komen ontdekken, en daarna ook in Gent, in de tentoonstelling « Een andere wereld ».
 
10:00 geleid bezoek in art & marges museum, tentoonstelling Gustav Mesmer
12:00 met auto-delen naar Gent
13:00 picknick in het dr. Guislain museum 
14:00 geleid bezoek aan de tentoonstelling « Een andere wereld » in dr. Guislain museum
 
Activiteit voorbehouden aan de vrienden van het art & marges museum. Lid worden van de vereniging van de vrienden van het art & marges museum : amisvrienden@artetmarges.be (jaarlijkse bijdrage : 30€ individuele bijdrage/50€ familiale bijdrage) 
 Zich inschrijven : 02 533 94 94 – amisvrienden@artetmarges.be

**Comment by pacomski** [comment]
Idem, merci de mettre en valeur ce qui doit être modifié (essayons en gras), et quelle illustration va où.

**Comment by FredericOszczak** [comment]
C'est fait. Pour les images, voir issue précédente.
