### ISSUE TITLE
Mise à jour page activ.html UK - texte et images à insérer

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#29]
**Creative Wednesdays (FR-NL)**
26.10.2016 14h30 --> 16h
30.11.2016 14h30 --> 16h
28.12.2016 14h00 --> 17h
25.01.2017 14h30 --> 16h

With reservation. For children from 6 to 12 years old 4€/child. Free for children from the neighbourhood.
Reservation 02/533 94 90 info@artetmarges.be

**Museum Night Fever**
11.03.2017
07:00 PM – 01:00 AM 
 
Gustav Mesmer was born in 1903 and died in 1994, but knew virtually nothing of the 20th century.  
Placed in a mental institution in Lautertal Valley when he was 26, he focused on his obsessive mission:  to create flying machines that would give him freedom. 

On this night of 11 March 2017, make Mesmer’s dream live on by creating your own fleet of flying machines to the rhythm of electro music and experimental ambiance. 

Participatory workshop:
The collectif 1soir [1 evening group] will invite you to create your flying machines in the span of an evening to supplement the open-ended installation. 

Concerts: 
19h15 Eric Kinny
20h00 Donatien Tomandini
20h45 Donatien Tomandini
 21h30 Kirsten Danst
22h15 Kirsten Danst
23h00 Real Trvth
23h45 Real Trvth
00h30 Eric Kinny

Music workshop, in partnership with Créahm-Brussels.
www.museumnightfever.be * 23 museums * Brussels * €15 /€11 (pre-sale) + €7 with after party. 
 
**Family activity in partnership with Le Wolf (FR)**
Saturday, 18.03.2017 + Saturday 20.05.2017
2:00 – 5:00 PM 
 
**Round table as part of the What is it? festival**
at Alice Gallery
30.03.2017
Participation of the art et marges musée in the round table on digital outsider art, organised by the What is it festival. 
 
**Fête de la gratuité**
02.04.2017
Guided tours on Erfgoeddag [Heritage Day]
23.04.2017
2:00 PM
The heritage day organised by the Vlaamse Gemeenschapscommissie [Flemish Community Commission] is devoted to the theme of “care” this year. 
…Art as care treatment… How is that reflected in the works of the collection of the art et marges musée? We ask the question during a guided tour of the trail of artists who created outside the usual artistic circuit – a discovery of outsider art. 

By reservation: 02 533 94 90 - info@artetmarges.be
Free admission and guided tour for persons who have registered.
 
**Guided tours of the Gustav Mesmer exhibition http://artetmarges.be/en/expo.html (art et marges musée) + Another world http://www.museumdrguislain.be/en/tentoonstellingen/Details/9050/another-world (Dr Guislain Museum, Ghent)** 
(an activity of the Friends of the art and margins museum) 

07.05.2017
The Dr Guislain Museum and the art et marges musée have one aspect in common:  an outsider art collection. In the spring of 2017, they will share another aspect:  hosting the works of Gustav Mesmer in their temporary exhibition. We invite you to discover the Gustav Mesmer exhibition in the art et marges musée, and extend your discovery of this artist to Ghent in an exhibition entitled “Een andere wereld” [Another World].
 
10:00 AM Guided tour of art et marges musée, Gustav Mesmer exhibition
12:00 noon Car pooling to Ghent 
01:00 PM picnic at the Dr Guislain Museum 
02:00 PM Guided tour of “Een andere wereld” at the Dr Guislain Museum
 
Activity reserved for the friends of the art et marges musée. Become a member of the association of the friends of the art et marges musée:   amisvrienden@artetmarges.be (annual dues: €30 for individuals;   €50 for families). 

Sign up: 02 533 94 94 – amisvrienden@artetmarges.be 
![activite-famille-avec-le-wolf_dsc5625_dxo](https://cloud.githubusercontent.com/assets/22938933/22687101/0592e83c-ed27-11e6-8653-b9f28fc8034c.jpg)
![erfgoeddag_dsc5148_dxo](https://cloud.githubusercontent.com/assets/22938933/22687102/0596e4a0-ed27-11e6-8a8d-be277ca712d7.jpg)
![matinee-creative_dsc5253_dxo](https://cloud.githubusercontent.com/assets/22938933/22687104/05994baa-ed27-11e6-8d5e-12a454c94959.jpg)
![museum night fever 2017](https://cloud.githubusercontent.com/assets/22938933/22687105/059cb484-ed27-11e6-8eea-40eb9e3ec32a.gif)
![visite-art-et-marges-et-dr-guislain](https://cloud.githubusercontent.com/assets/22938933/22687103/0598a16e-ed27-11e6-84d3-97867f829541.jpg)

**Comment by FredericOszczak** [comment]
c'est ok comme ça ?

**Comment by pacomski** [comment]
Est ce qu'il n'y aurait pas une erreur pour les creatives Wednesday ? 
Je ne les mets pas pour le moment
