### ISSUE TITLE
Rencontres intergalactiques coupée sur la version mobile du site http://artetmarges.be

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#458]
Le "intergalactiques" du titre est sur 2 lignes sur la version mobile du site, il faudrait le mettre sur une ligne.

**Comment by pacomski** [comment]
C'est normal qu'il soit sur deux ligne étant donné qu'il est un peu long, par contre j'ai mis une césure plus propre.
