### ISSUE TITLE
Favicon avec le nouveau logo

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#46]
Sur certaines pages, le nouveau logo apparaît en favicon, parfois pas (sur mon PC c'est le cas pour la page activités par exemple. Sur le PC de Tatiana, c'est encore l'ancien logo "&" qui apparaît).

Problème avec nos navigateurs ? Autre chose ?

**Comment by pacomski** [comment]
probablement une question de cache sur vos navigateurs.
Est ce que ça rentre dans l'ordre une fois celui-ci vidé ?
infos ici pour vider le cache : http://www.viderlecache.fr/

**Comment by pacomski** [comment]
je viens de trouver une page qui n'avait pas de favicon (activ.html /fr)
C'est réglé

**Comment by FredericOszczak** [comment]
Merci !
J'ai vidé le cache, ça fonctionne et montrerai la procédure à Tatiana.
