### ISSUE TITLE
ajouter le dossier pédagogique à "expositions" FR http://artetmarges.be/fr/expo.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#478]
Ajouter un lien vers le dossier pédagogique FR (envoyé par wetransfer) en dessous de "Dossier de presse et images" et l'appeler "Dossier pédagogique"

**Comment by ninwille** [comment]
Il semble que le lien we-transfert ne soit pas parvenu. Pouvez-vous le renvoyer? Un grand merci.
