### ISSUE TITLE
Mise à jour pages expo.html FR+NL+UK

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#5]
Pour ce lundi 30/01

"Sauver le monde ?" (FR), "De wereld redden?" (NL), "Save the world ?" (UK) et tout le contenu de ces articles (dates, photo, légende, noms des artistes, logos) doivent disparaître de la section "ACTUELLE".

Est-il possible de mettre le tout sous une section "PRÉCÉDEMMENT" (FR), "VORIGE" (NL), "PREVIOUS" (UK) ?

L'exposition Gustav Mesmer peut rester sous la section "À VENIR" (FR, NL et UK).

Sous la section "ACTUELLE" (FR), insérer le texte suivant : Le musée est fermé pendant le montage de la prochaine exposition "Gustav Mesmer. L'Icare de Lautertal"
On vous donne rendez-vous le jeudi 9 février dès 18 heures pour le vernissage.
L’équipe du Art et Marges musée.

Sous la section "ACTUELLE" (NL), insérer le texte suivant : Het museum is gesloten tijdens het opbouwen van de toekomstige tentoonstelling "Gustav Mesmer, de Icarus van het Lautertal"
Op donderdag 29 september bent u van harte welkom voor de vernissage (18u).
Het Art et Marges museum team.

Sous la section "ACTUELLE" (UK), insérer le texte suivant :

The museum is closed during change of exhibition. See you on 9 February at 6PM for the opening of our new exhibition “Gustav Mesmer, Icarus from the Lautertal”.
The Art et Marges museum team.

Merci.

**Comment by pacomski** [comment]
C'est fait - 25min
