### ISSUE TITLE
Rubriques "AGENDA" et "VORIGE" de la page activ.html (NL) + "AGENDA" et "PREVIOUS" de la page activ.html (UK) collées

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#6]
J'ai remarqué que les rubriques "AGENDA" ET "VORIGE" (dans les cartouches rouges) étaient collées l'une à l'autre.

Même chose pour "AGENDA" et "PREVIOUS" de la page activ.html (UK)

Y a -t-il moyen de les séparer et de respecter la structure (ordre chronologique) comme sur la page activ.html (FR) ?

Merci.

**Comment by pacomski** [comment]
Il semble que ce soit normal : si l'on en crois les dates, il n'y a pas de contenu à venir, tout est déjà passé. 

J'ai enlevé le label "VORIGE" et "PREVIOUS" en attendant plus de détails...

(10min)
