### ISSUE TITLE
ajouter noms artistes fr http://www.artetmarges.be/fr/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#618]
Zebedee Armstrong ;  Richard Bawin ; Klaus Beyer ; Pearl Blauvelt ; Denis Boudouard ; Heather Copus ; Jean Crié ; Bridget Cronnin ; Gabriel Evrard ; Charles Ferguson ; Howard Finster ; Giovanni Galli ; Affiches de cinéma du Ghana ; William A. Hall ; Herman Hayes ; Alexandre Heck ; Ismael Hespel ; Paa Joe ; Daniel Johnston ; Bodys Isek Kingelez ; Camille Lavaud Benito ; Jean Leclercq ; Karen May ; James Miles ; Matthieu Morin ; Wilfrid Morin ; Edward Nagrodzki ; Melvin Edward Nelson ; Martín Ramírez ; Lance Rivers ; Prophet Royal Robertson ; William Scott ; Welmon Sharlhorne ; Earl Wayne Simmons ; Jean Smilowski ; Ichiwo Sugino ; Éric Tabuchi ; Ionel Talpazan ; Dominique Théate ; Warren Van Ess ; Ricky Willis ; Wesley Willis ; Joseph Yoakum ; Jonathan Velazquez ; Julien Bancilhon

**Comment by ninwille** [comment]
ces noms sont-ils bien à ajouter à l'expo à venir?

**Comment by FredericOszczak** [comment]
Non dans l'expo actuelle !
