### ISSUE TITLE
Splashscreen to do

### ISSUE THREAD

**Issue by pacomski** [communicationartetmarges/art-et-marges#640]

**Comment by pacomski** [comment]
Est-ce que le splashscreen s'affiche également sur le smartphone ? Pour ma part je pense pas que se soit nécessaire car Sukrii n'a pas fourni de version verticale.

**Comment by ninwille** [comment]
Moi ça fonctionne sur Mozilla mais pas sur Chrome... où j'ai également une grosse croix, et quand je descends j'ai le "play" et puis la video. Quand je clique sur le play, y a tout qui disparait mais la musique joue ;)

**Comment by pacomski** [comment]
ok, super, on pourra débugger ça alors, car je n'arrivais pas le reproduire...

**Comment by pacomski** [comment]
c'est simplement du cache de navigateur
