### ISSUE TITLE
modification slider : images glitches / bug visuels

### ISSUE THREAD

**Issue by pacomski** [communicationartetmarges/art-et-marges#644]

**Comment by pacomski** [comment]
Je manque d'infos à ce sujet.
Est ce que c'est possible d'avoir des screenshot + navigateur utilisé ?

**Comment by vvvvcccc** [comment]
Problème avec le slider: la légende n'est pas alignée à gauche (cf. document design)

<img width="829" alt="Capture d’écran 2019-11-11 à 16 45 32" src="https://user-images.githubusercontent.com/29175301/68603362-6b557180-04a8-11ea-87c4-726784b4b312.png">

**Comment by vvvvcccc** [comment]
problème également au niveau des flèches :
quand je disais "elles changent de sens" je pensais à quelque chose de se style :
[](https://www.moussepublishing.com/)

**Comment by vvvvcccc** [comment]
problème d'interlignage différents dans les titres :
<img width="536" alt="Capture d’écran 2019-11-11 à 17 36 26" src="https://user-images.githubusercontent.com/29175301/68604040-db182c00-04a9-11ea-8166-2fb3925f626c.png">

**Comment by pacomski** [comment]
a suivre dans les issues séparées
