### ISSUE TITLE
move extramuros exhibitions to front page, above upcoming 

### ISSUE THREAD

**Issue by pacomski** [communicationartetmarges/art-et-marges#646]
(currently in Activities)

**Comment by pacomski** [comment]
Il faudrait idéalement quelques directions graphiques pour cela.

**Comment by ninwille** [comment]
actuellement ça ressemble à ça: 
![Screenshot from 2019-11-15 10-55-40](https://user-images.githubusercontent.com/47986775/68934312-c16f3100-0796-11ea-90b7-b22b79769a95.png)

**Comment by ninwille** [comment]
@vvvvcccc

**Comment by ninwille** [comment]
J'ai mis en ligne, comme ça tu peux voir le passage vers les expos passées

**Comment by pacomski** [comment]
ping @vvvvcccc
