### ISSUE TITLE
Splash screen "L'amérique"

### ISSUE THREAD

**Issue by vvvvcccc** [communicationartetmarges/art-et-marges#651]

**Comment by vvvvcccc** [comment]
Il n'y pas de flou sur le background sur Firefox mais sur Chrome c'est ok :

<img width="1280" alt="Capture d’écran 2019-11-11 à 17 38 13" src="https://user-images.githubusercontent.com/29175301/68604197-4104b380-04aa-11ea-8d52-efa6ff340dfa.png">

**Comment by vvvvcccc** [comment]
Le button lecture est énorme comparé au reste, c'est voulu ?

**Comment by vvvvcccc** [comment]
La croix en haut à droite est un chouia trop grosse, est-il possible de la réduire un peu ?

**Comment by pacomski** [comment]
@vvvvcccc idem : une issue par question / chose à faire, merci ;)

**Comment by pacomski** [comment]
a voir dans les issues séparées
