### ISSUE TITLE
Toutes pages - problème implémentation design

### ISSUE THREAD

**Issue by vvvvcccc** [communicationartetmarges/art-et-marges#652]

**Comment by vvvvcccc** [comment]
problème d'interlignages différents dans les titres :
<img width="536" alt="Capture d’écran 2019-11-11 à 17 36 26" src="https://user-images.githubusercontent.com/29175301/68604040-db182c00-04a9-11ea-8166-2fb3925f626c.png">

**Comment by vvvvcccc** [comment]
le surlignement des liens est un poil trop gras, est-il possible de le réduire un peu de manière à ce qu'il s'harmonise avec la typo ? merci

<img width="179" alt="Capture d’écran 2019-11-11 à 17 47 16" src="https://user-images.githubusercontent.com/29175301/68604742-6d6cff80-04ab-11ea-9b00-e07d6695cca1.png">

**Comment by vvvvcccc** [comment]
sur la version mobile, le titre disparait chez moi :
<img width="423" alt="Capture d’écran 2019-11-11 à 17 49 34" src="https://user-images.githubusercontent.com/29175301/68604869-b2913180-04ab-11ea-8b0a-8a4b6d8f4f7d.png">

**Comment by vvvvcccc** [comment]
Est-il possible également de réduire la taille du corps (et interlignage) dans le menu afin de l'harmoniser avec celle des titres ? 

<img width="297" alt="Capture d’écran 2019-11-11 à 17 52 02" src="https://user-images.githubusercontent.com/29175301/68605069-14519b80-04ac-11ea-8b2a-816115cc4437.png">

**Comment by vvvvcccc** [comment]
problème avec le menu en NL:

<img width="373" alt="Capture d’écran 2019-11-11 à 17 53 39" src="https://user-images.githubusercontent.com/29175301/68605186-4105b300-04ac-11ea-8d63-794f7c2d1f48.png">

**Comment by vvvvcccc** [comment]
est-il possible de passer le line-height du corps de labeur de 110% à 115% ?
<img width="1120" alt="Capture d’écran 2019-11-11 à 17 56 31" src="https://user-images.githubusercontent.com/29175301/68605448-b6718380-04ac-11ea-9d88-8c8847cd711c.png">

**Comment by vvvvcccc** [comment]
est-il possible de supprimer la marges blanche des scrollbars sur Firefox ? Et si possible, de les avoir rectangulaire comme sur Chrome ? merci

<img width="474" alt="Capture d’écran 2019-11-11 à 17 58 16" src="https://user-images.githubusercontent.com/29175301/68605624-094b3b00-04ad-11ea-9443-04ad71e6a82a.png">

**Comment by pacomski** [comment]
@vvvvcccc merci de faire une issue par issue ;)

**Comment by pacomski** [comment]
à voir dans les issues séparées
