### ISSUE TITLE
Ajouter activité D'un musée à l'autre fr http://www.artetmarges.be/fr/activ.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#664]
Art et marges musée x Musée juif de Belgique

Samedi 30.11.2019 14:00-16:00

![image](https://user-images.githubusercontent.com/22938933/69152076-1afb9680-0adc-11ea-9cc1-3a8928c5f621.png)

Deux musées voisins, une exposition aux accents US dans chacun de nos lieux ET une exposition commune !

3 bonnes raisons pour vous proposer une après-midi guidée entre nos deux musées.

Nos guides vous accompagneront du Art et marges musée au Musée juif pour vous présenter le meilleur des trois expositions :

- "L'Amérique n'existe pas" au Art et marges musée

- "Carte blanche au Art et marges musée" au Musée juif de Belgique

- "Superheroes never die" (au Musée juif de Belgique)

Rendez-vous à 14h au Art et marges musée (rue Haute, 314 - 1000 Bruxelles - metro/tram/bus : Porte de Hal)

Tarif unique : 7€ par personne / places limitées (20 pers.)

Réservation : http://www.mjb-jmb.org/art-et-marges-x-…juif-de-belgique/

**Comment by ninwille** [comment]
Le lien ci-dessus étant incomplet, j'imagine que le bon lien est bien: 
http://www.mjb-jmb.org/art-et-marges-x-musee-juif-de-belgique?
(même s'il ne renvoit pas vers une page de réservation?)

**Comment by FredericOszczak** [comment]
justement, le lien initialement transmis était mauvais.
Le bon lien est le suivant: https://www.eventbrite.ca/e/82809925717

**Comment by ninwille** [comment]
Ok, merci, je change ça !
