### ISSUE TITLE
ajout d'un article colonne Agenda sur la page http://www.artetmarges.be/fr/activ.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#758]
![MMD en bandeau d'événement1](https://user-images.githubusercontent.com/22938933/75997885-4b870500-5f00-11ea-86d4-26480cf78a17.jpg)

VISITES GUIDÉES PAR LES VOISINS DU ART ET MARGES MUSÉE
21 MARS 2020 14:00 et 15:30 

Dans le cadre du festival Marolles Ma Divercité, le Caria asbl, la maison des jeunes Le 88 et Art et marges s’associent pour vous proposer des visites guidées par les voisins du musée.
Nos guides d’un jour se sont immergés dans l’exposition « Le Cœur au ventre » et vous emmènent à présent dans un parcours qui s’arrête sur leurs coups de cœur. Une visite, avec un petit quelque chose en plus…

gratuit, sans réservation (arriver 15’ avant le départ de la visite)

**Comment by ninwille** [comment]
J'imagine que cet évènement n'aura pas lieu et que du coup ça ne vaut pas la peine de l'annoncer sur le site...?

**Comment by FredericOszczak** [comment]
oui, en effet. Excuse moi, j'ai oublié de supprimer la commande ;-)
