### ISSUE TITLE
Ajout dans la colonne AGENDA sur la page http://www.artetmarges.be/fr/activ.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#765]
ATELIER EN FAMILLE

Prêts pour la rencontre entre les fantômes des œuvres et votre créativité ??? En partant de leurs ombres, nous imaginerons librement les œuvres qui peuplent l’exposition “Le Cœur au ventre” avant d’aller les rencontrer en chair et en os !
 
Au menu : atelier de monotype, présentation ludique de l’exposition “Le Coeur au ventre”, joie et bonne humeur !

sur réservation : info@artetmarges.be
Gratuit - Dans le cadre du ERFGOEDDAG
FR-NL

**Comment by ninwille** [comment]
Peut-il faut-il donner une date?  :)
