### ISSUE TITLE
modification barre d'onglet http://www.artetmarges.be/nl/musee.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#789]
Barre d'onglet: remplacer "expositions" par "Museum"

**Comment by ninwille** [comment]
Hello, je ne suis pas sure d'avoir bien compris ce qu'il fallait remplacer. Dans les onglets, il y a "Tentoonstellingen" ou "Museum"... mais pas "expositions"?

**Comment by FredericOszczak** [comment]
Bonjour, 
pour http://www.artetmarges.be/nl/musee.html , "expositions" s'affiche dans la barre d'onglets internet au lieu de "Museum" 
voilà un petit screenshot peut-être plus démonstratif:
![barre onglet](https://user-images.githubusercontent.com/22938933/87789283-14761800-c83f-11ea-905c-2fe570387eca.JPG)

**Comment by ninwille** [comment]
Ok, j'ai vu! J'en ai profité pour remplacer tous les autres titres qui étaient aussi érronés. Il faudra peut-être recharger la page pour que ça prenne effet de votre côté.
