### ISSUE TITLE
Suppression http://www.artetmarges.be/fr/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#846]
Exposition -> Actuelle 

Supprimer tout le paragraphe 'Reouverture' et la grosse photo des mains et de la bouteille.

**Comment by FredericOszczak** [comment]
Je ne vois pas la suppression de l'article :( est-ce normal ?

**Comment by ninwille** [comment]
effectivement, erreur de ma part, désolée!

**Comment by FredericOszczak** [comment]
Pas de soucis ! Merci beaucoup ! 
Le musée va fêter ses 10 ans et lancer une publication, c'est un événement important pour nous. De fait, il va y avoir pas mal d'ajout à faire sur le site web ces prochains temps. Nous attendons beaucoup de visite dessus et les gens devront pouvoir trouver les informations mises à jour rapidement. 
N'hésitez pas à me dire comment vous voulez qu'on procède pour vous faciliter la vie, si je dois indiquer des ordres de priorité ou donner une forme spécifique à mes 'issues' ?
Je suis disponible par téléphone au besoin (+32 (0) 2 533 94 90)
Merci pour votre aide, 

Excellente journée ! 

Marcelline
