### ISSUE TITLE
URGENT ! Changement image http://www.artetmarges.be/fr/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#869]
À VENIR
Changer l'image des personnages par celle-ci (dites moi si le format ne correspond pas, je ne sais pas quels sont les dimensions d'image optimum pour les différentes rubriques du site) Merci ! : 

![facebook-banner-150](https://user-images.githubusercontent.com/22938933/93219708-edb75d80-f76b-11ea-86c4-e1d08439064c.jpg)

**Comment by ninwille** [comment]
Hello, effectivement l'image est fort coupée avec ce format là. L'image précédente était en 1000x730, celle-ci en fait plutôt 1700x700. Si c'est possible de l'ajuster c'est mieux, merci!

**Comment by FredericOszczak** [comment]
Et voici ! 

![facebook-banner-event-300dpi](https://user-images.githubusercontent.com/22938933/93612273-9a454980-f9cf-11ea-883e-e3695e65986d.jpg)

**Comment by ninwille** [comment]
Hello, la nouvelle image était encore trop aplatie pour apparaitre en entier (elle était cropée à droite). J'ai donc ajouté du blanc autour pour que ça rentre, pour pouvoir quand même l'afficher tout de suite.

**Comment by FredericOszczak** [comment]
Ok super merci ! Ca rend niquel ! 

Sais tu du coup la dimension qu'il faut ? Y aurait-il moyen d'avoir une liste de tous les formats images du site et leur correspondance ? A qui puis-je demander ça ? Au web designer ?

**Comment by pacomski** [comment]
hello! Je me glisse dans la discussion.. 
@vvvvcccc doit avoir une idée sur la question ;)

**Comment by ninwille** [comment]
Je pense que jusqu'à présent les images n'ont pas toutes la même taille mais ont partout des dimensions proportionnelles à environ 1000x700. (en tout cas ça ça fonctionne bien). 
Il y a juste les vignettes de la partie musée qui sont d'une autre dimension (carrées), et les fiches d'artistes qui permettent d'avoir des images en portrait ou paysage.
