### ISSUE TITLE
Echange mention VS image http://www.artetmarges.be/fr/info.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#876]
Quand on scroll tout en bas de cette page, on voit apparaître "Design: Victor Coupaud (DEAL) et Sukrii Kural"

Supprimer cette mention et ajouter à la place l'image suivante :  
![Pied de page](https://user-images.githubusercontent.com/22938933/93613369-12f8d580-f9d1-11ea-946d-51089c79b23a.jpg)

Merci !

**Comment by ninwille** [comment]
C'est fait, mais comme pour le logo, il faudra sans doute faire un point graphique pour que ça soit intégré correctement.

**Comment by FredericOszczak** [comment]
Ok avec qui dois-je voir cela ?

**Comment by ninwille** [comment]
Je pense que c'est @vvvvcccc  qui s'occupe du graphisme chez vous.
