### ISSUE TITLE
AJOUT http://www.artetmarges.be/fr/musee.html dans COLLECTION

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#879]
**AJOUTER:**

BAILLY
Carol BAILLY (USA, 1955-)
![marge-02-0045 1](https://user-images.githubusercontent.com/22938933/93713474-81b66a00-fb5c-11ea-85c2-507d4a07ef3d.jpg)

BORGHI
Anacleto BORGHI (Italie, 1921-2008)
![BORGHI](https://user-images.githubusercontent.com/22938933/93712345-99d6bb00-fb55-11ea-9a6d-305cdbad84ac.jpg)

BOTTEMANE
Dominique BOTTEMANE (Belgique ,1961-)
![Bottemane 90](https://user-images.githubusercontent.com/22938933/93712356-bbd03d80-fb55-11ea-8217-15f925610ba9.jpg)

CONDYLIS
Phillippe CONDYLIS (France, 1959-)
![CONDYLIS-02-0025](https://user-images.githubusercontent.com/22938933/93712376-d1456780-fb55-11ea-8993-0454b74dd2e1.jpg)

COPENAUT
Martine COPENAUT (Belgique, 1955-2004)
![COPENAUT-02-0082 1](https://user-images.githubusercontent.com/22938933/93712402-f8039e00-fb55-11ea-92f5-29a7af44f0a0.jpg)

CYCON
Kazimierz CYCON (Pologne, 1931-2004)
![Cycon 133](https://user-images.githubusercontent.com/22938933/93712421-15386c80-fb56-11ea-9d41-913b78fc7f4e.jpg)

DAHYOT
Caroline DAHYOT (France, 1968-)
![dahyot](https://user-images.githubusercontent.com/22938933/93712443-3c8f3980-fb56-11ea-82aa-e7e05d6cabc4.jpg)

D’HONDT
Hylde D’HONDT (Belgique, 1956-)
![DHONDT](https://user-images.githubusercontent.com/22938933/93712529-b9baae80-fb56-11ea-834e-c924d7b3d535.jpg)

DE BRUYNE
Heide DE BRUYNE (Belgique, 1955-)
![de bruyne](https://user-images.githubusercontent.com/22938933/93712465-592b7180-fb56-11ea-96d4-798b649f110d.jpg)

DE SMEDT
Willy De SMEDT (Belgique, 1943-)
![de smedt](https://user-images.githubusercontent.com/22938933/93712479-6f393200-fb56-11ea-8ce1-d096c22dd222.jpg)

DE VRIES
Sieberen De VRIES (Pays-Bas, 1969)
![de vries](https://user-images.githubusercontent.com/22938933/93712497-8546f280-fb56-11ea-9340-b55609b9830a.jpg)

DERKENNE
Eric DERKENNE (Belgique, 1960-2014)
![derkenne](https://user-images.githubusercontent.com/22938933/93712505-9859c280-fb56-11ea-9415-de1b1c660b5e.jpg)

Di GIOVANNI
Curzio Di GIOVANNI (Italie, 1957-)
![Digiovanni 1782](https://user-images.githubusercontent.com/22938933/93712561-f2f31e80-fb56-11ea-9840-f64354cccde2.jpg)

ETIENNE
Frédéric ETIENNE (Belgique, 1965-)
![etienne](https://user-images.githubusercontent.com/22938933/93712577-0bfbcf80-fb57-11ea-8cd6-75ef52b96893.jpg)

FLEURI
Yves-Jules FLEURI (France, 1960)
![fleuri](https://user-images.githubusercontent.com/22938933/93712583-1b7b1880-fb57-11ea-86d7-476b3b1ea628.jpg)

FRANCEUS
Cécile FRANCEUS (Belgique, 1962-2008)
![FRANCEUS](https://user-images.githubusercontent.com/22938933/93712593-2fbf1580-fb57-11ea-97da-1a998b18578b.jpg)

FRANKLIN
FRANKLIN (Portugal)
![franklin](https://user-images.githubusercontent.com/22938933/93712606-41a0b880-fb57-11ea-8f4a-53661c3e6806.jpg)

GALLIENI
Jill GALLIENI (France, 1948-)
![gallieni](https://user-images.githubusercontent.com/22938933/93712618-51b89800-fb57-11ea-98f5-f09fc17f9d30.jpg)

GERARD
Irène GERARD (Belgique, 1958-)
![gerard](https://user-images.githubusercontent.com/22938933/93712637-672dc200-fb57-11ea-93f6-b23b48a174b1.jpg)

GILL
Madge GILL (Angleterre, 1882-1961)
![Gill madge](https://user-images.githubusercontent.com/22938933/93712658-89bfdb00-fb57-11ea-8dc5-66bcb8ecf37d.jpg)

GOYON
Michel GOYON (France, 1963-)
![goyon](https://user-images.githubusercontent.com/22938933/93712660-8e848f00-fb57-11ea-9dd0-f5d340e399f5.jpg)

HAUS
Oscar HAUS (Belgique, 1939-2018)
![haus](https://user-images.githubusercontent.com/22938933/93712681-aa883080-fb57-11ea-90ae-55d0c2d12ac9.jpg)

HEFFINCK
Hendrik HEFFINCK (Belgique, 1965-)
![Hendrik  682 (1)](https://user-images.githubusercontent.com/22938933/93712732-f6d37080-fb57-11ea-96b4-fee0f93b3ca4.jpg)

HEYLIGEN
Jean-Marie HEYLIGEN (Belgique, 1961-)
![Heyligen001](https://user-images.githubusercontent.com/22938933/93712762-11a5e500-fb58-11ea-8be9-a35b045dd061.jpg)

HEYMANS
Brenda HEYMANS (Belgique, 1953-1991)
![heymans](https://user-images.githubusercontent.com/22938933/93712765-17032f80-fb58-11ea-954a-0df9b8cf819b.jpg)

HOLLANDER
Jeroen HOLLANDER (Belgique, 1976-)
![hollander](https://user-images.githubusercontent.com/22938933/93712787-3c903900-fb58-11ea-92ee-98a5a0c088f0.jpg)

HOUIS
David HOUIS (Belgique, 1989-)
![houis](https://user-images.githubusercontent.com/22938933/93712789-41ed8380-fb58-11ea-8535-709e4a8c5205.jpg)

KNOPF
Solange KNOPF (Belgique, 1957-)
![knopf](https://user-images.githubusercontent.com/22938933/93712809-65183300-fb58-11ea-90b6-a5c6e44e4e3e.jpg)

LAENEN
Karel LAENEN (Belgique, 1956)
![laenen](https://user-images.githubusercontent.com/22938933/93712819-72352200-fb58-11ea-9f80-6e00314bca4d.jpg)

MARSHALL
Francis MARSHALL (France, 1946-)
![marshall](https://user-images.githubusercontent.com/22938933/93712856-ac062880-fb58-11ea-9ada-8ce500ee1951.jpg)

MARTENS
Dirk MARTENS (Belgique, 1970-)
![martens](https://user-images.githubusercontent.com/22938933/93712859-b3c5cd00-fb58-11ea-8302-42e40cb0d481.jpg)

MARX
Wolfgang MARX (Allemagne, 1946-2011)
![Marx Wolfgang 2009 16](https://user-images.githubusercontent.com/22938933/93712877-d0fa9b80-fb58-11ea-97ab-728b847c7b11.jpg)

MESSOU
Ezekiel MESSOU (Bénin, 1971-)
![messou](https://user-images.githubusercontent.com/22938933/93712884-d952d680-fb58-11ea-889b-7f86aafe1d67.jpg)

MICHEL
Raphaël MICHEL (France, 1988-)
![michel](https://user-images.githubusercontent.com/22938933/93712912-ff787680-fb58-11ea-98f7-a4d16c13b724.jpg)

MVUMBI
Antoine MVUMBI (Belgique, 1974-)
![mvumbi](https://user-images.githubusercontent.com/22938933/93712913-030bfd80-fb59-11ea-80af-32dc4d1ed827.jpg)

PELOSI
Marilena PELOSI (Brésil, 1957-)
![pelosi](https://user-images.githubusercontent.com/22938933/93712991-8299cc80-fb59-11ea-9251-5cf59f37549b.jpg)

PIERLOT
Rémy PIERLOT (Belgique, 1945-)
![pierlot](https://user-images.githubusercontent.com/22938933/93713004-87f71700-fb59-11ea-91c8-f74f246d436f.jpg)

PRUES
André PRUES (Belgique, 1957)
![prues](https://user-images.githubusercontent.com/22938933/93713071-06ec4f80-fb5a-11ea-91c0-632a8c3309ef.jpg)

RASMUSSEN
Kenneth RASMUSSEN (Danemark, 1971-)
![rasmussen](https://user-images.githubusercontent.com/22938933/93713088-1d92a680-fb5a-11ea-9781-0cfc220d9ed1.jpg)

REMACLE
Christine REMACLE (Belgique, 1967-2014)
![Remacle 1224](https://user-images.githubusercontent.com/22938933/93713400-ed4c0780-fb5b-11ea-82a3-6be67fe08632.jpg)

REYNS
Fernanda REYNS (Belgique, 1957-)
![reyns](https://user-images.githubusercontent.com/22938933/93713099-271c0e80-fb5a-11ea-877b-d658fdf24f4a.jpg)

RIBEIRO
Pedro RIBEIRO (Portugal, 1990-)
![ribeiro](https://user-images.githubusercontent.com/22938933/93713148-55015300-fb5a-11ea-9ad6-09e95eaa4445.jpg)

RICCIO
Melina RICCIO (Italie, 1951-)
![riccio](https://user-images.githubusercontent.com/22938933/93713171-72362180-fb5a-11ea-8ae8-191b835905b6.jpg)

ROSTENNE
Jean-Pierre ROSTENNE (Belgique, 1942-2017)
![Rostenne 1B](https://user-images.githubusercontent.com/22938933/93713175-782c0280-fb5a-11ea-83db-ab6389a58e99.jpg)

SAKAI
Tomoaki SAKAI (Japon, 2001-)
![sakai](https://user-images.githubusercontent.com/22938933/93713204-98f45800-fb5a-11ea-9b42-2ae1a6973e12.jpg)

SERVAIS
Anny SERVAIS (Belgique, 1952-2009)
![Servais 2538](https://user-images.githubusercontent.com/22938933/93713208-9c87df00-fb5a-11ea-8db8-c1708e7d114f.jpg)

TARGA
Mohammed TARGA (Maroc, 1960-)
![targa](https://user-images.githubusercontent.com/22938933/93713231-bfb28e80-fb5a-11ea-9ed0-a68e30b585e3.jpg)

THEATE
Dominique THEATE (Belgique, 1958-)
![theate](https://user-images.githubusercontent.com/22938933/93713232-c4774280-fb5a-11ea-99a3-be7255a422a3.jpg)

VINCKE
Pascale VINCKE (Belgique, 1974-)
![vincke](https://user-images.githubusercontent.com/22938933/93713254-e2dd3e00-fb5a-11ea-8393-7de5a175dc11.jpg)

VIZCAÏNO
Jacqueline VIZCAÏNO (Algérie, 1937-)
![vizcaïno](https://user-images.githubusercontent.com/22938933/93713257-e7095b80-fb5a-11ea-9cfc-d7e356b6bcca.jpg)

WUILBEAUX
Jean-Michel WUILBEAUX (France, 1968-)
![Wuilbeaux2334](https://user-images.githubusercontent.com/22938933/93713279-099b7480-fb5b-11ea-8d7a-4c91cc6d3119.jpg)

**Comment by ninwille** [comment]
Hello, voilà qui est fait. Pour être plus efficace, une prochaine fois, n'hésitez pas à envoyer un dossier (.zip par exemple) avec toutes les images d'un coup (ça évite de devoir les télécharger et les renomer une à une), en nommant bien les images sans accents ni espaces. 
Pour les infos à propos des artistes, idéalement, c'est mieux de nous envoyer le csv complété. Là je l'ai complété avec les infos reçues, je vous joins la dernière version. (un fichier par langue).
[collection-all-csv.zip](https://github.com/communicationartetmarges/art-et-marges/files/5271691/collection-all-csv.zip)

**Comment by FredericOszczak** [comment]
Super ! Merci beaucoup ! On fera ça, je transmets à la stagiaire qui s'en occupe :) Belle journée !
