### ISSUE TITLE
Ajouts vidéos http://www.artetmarges.be/fr/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#896]
Bonjour Nina, 

Par quel moyen puis-je t'envoyer des vidéos à mettre sur le site ? C'est trop lourd pour ici même en ZIP ?

Serait-ce possible de mettre en miniatures des vidéos dans EXPOSITION ACTUELLE - LE COEUR AU VENTRE Sous le dossier pédagogique de l'expo ? Est-ce possible lorsqu'on clique dessus de les agrandir ? 

Merci pour ton aide !

**Comment by ninwille** [comment]
Hello, pas de soucis pour l'envoi de vidéo, par WeTransfer par exemple. 
Pour la miniature ça serait intéressant de savoir comment le présenter au mieux, peut-être avoir un retour de @vvvvcccc ?

**Comment by FredericOszczak** [comment]
Et voici : 
https://we.tl/t-vAb9sUD5yf

Pareil si ça pouvait être mis en ligne comme tu peux et @vvvvcccc adaptera après ! Il faudrait que ces vidéos soient visibles le plus vite possible avant la fin de l'expo en cours ! 

Merci !

**Comment by ninwille** [comment]
Hello, 
Je ne m'attendais pas à ce qu'il y ait 10 videos :) On est en train de tester comme ça mais idéalement (et pour la suite si ça se reproduit) ça serait mieux de les mettre sur votre compte youtube (ou sur un compte vimeo) et qu'on intègre la vidéo à partir de là. Ca évitera de surcharger le dépot (c'est lourd et là ça a du mal a passer).

**Comment by ninwille** [comment]
Re-hello !
Bon, en fait github refuse le transfer car c'est trop lourd, donc il va effectivement falloir mettre vos vidéos ailleurs. Visuellement ça ne changera pas grand chose ensuite, on pourra les intégrer sans soucis.

**Comment by FredericOszczak** [comment]
Ok ! Je vais m'occuper de ça ;) Merci !!

**Comment by FredericOszczak** [comment]
Hello ! Et voici Nina :) 

https://youtu.be/i63rMD9GGDU

https://youtu.be/Qr4CXBtzQLQ

https://youtu.be/Rax0B4SMzVI

https://youtu.be/bLn88rcUhjY

https://youtu.be/aE6iM3QSzQ8

https://youtu.be/jhpWVVYv1RI

https://youtu.be/fzhzvjQQVU4

https://youtu.be/OJhBgyPZdVU

https://youtu.be/D_VN-rNQjSU

https://youtu.be/38e3aMhhls0

Merci beaucoup ! Dis moi si je peux faire autre chose pour te faciliter la vie :)
