### ISSUE TITLE
Ajout http://www.artetmarges.be/fr/musee.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#901]
Dans LA COLLECTION A mettre en tout premier.

A l’occasion de l’anniversaire des 10 ans du musée, les éditions CFC publient l’ouvrage Art et Marges musée qui met en lumière la collection du musée et ses artistes. Il réunit quelque deux cents œuvres d’art brut et outsider issues de la collection qui en compte au total plus de 4000. Des créations singulières conçues par des artistes autodidactes au mode d’expression unique et à l’inventivité foisonnante contextualisées par celles et ceux qui ont fait et font le Art et marges musée. A travers un va-et-vient entre textes théoriques, entretiens, témoignages et anecdotes… laissez vous conter le Art et marges musée.

![CFC_A M_Inside_Cover_LD](https://user-images.githubusercontent.com/22938933/94707758-1c286180-0344-11eb-8056-62fb9b078d14.jpg)

**Comment by ninwille** [comment]
Hello, 
ici aussi ça serait intéressant d'avoir un retour graphique plus précis, pour que ça s'intègre au mieux dans le graphisme actuel... voir si c'est mieux au dessus de "historique" à gauche, ou au dessus de la collection proprement dite (si oui comment), ou sur une autre page... @vvvvcccc ?

**Comment by FredericOszczak** [comment]
Hello ! 

En attendant la réponse de @vvvvcccc est-ce possible de le mettre en ligne ? Victor verra nos besoins et adaptera le design en fonction. 
C'est assez urgent comme le lancement approche ! 

Merci Nina ;)
