### ISSUE TITLE
Ajout Article http://www.artetmarges.be/fr/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#920]
Nouvelle demande un peu particulière ! 

Est-il possible d'ajouter un article (avec la barre grise) Dans le menu Exposition - Au dessus de 'ACTUELLE'

Titre (dans le gris) : INTRODUCTION

Et en dessous mettre cette vidéo avec l'écran de la largeur de la colonne : 
https://youtu.be/lhZhAhCAMRQ

Tiens moi au courant ;)

**Comment by ninwille** [comment]
Hello, pas de soucis pour le faire. Sache juste que ces changements demandent à chaque fois plus de temps que ce qu'on a l'habitude de faire pour vous... et que votre facture risque donc de gonfler si on a souvent ce genre de demandes.
Par ailleurs, si on se met à mettre pas mal de videos sur le site il peut être utile de décider d'une liste de possibilités limitée comme "video sur toute la largeur", "liste de videos", ... comme ça on crée des styles fixes pour ces cas là et on ne doit pas le ré-adapter à chaque fois.

**Comment by FredericOszczak** [comment]
Super merci Nina ! 
Ok c'est noté. 

Oui c'est bien ces deux options : "video sur toute la largeur", "liste de videos" -> avec des miniatures ça serait en effet niquel !
