### ISSUE TITLE
Pour LUNDI ajout ENG - message fermeture du musée pour montage

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#930]
Nina, Sarah m'a dit qu'un message et sa forme "tout prêts" existaient pour la fermeture du musée sur la période de montage des nouvelles expositions. Peux-tu le poster s'il te plait ? Je ne sais pas comment et ou il apparait ?

Titre : CLOSURE FOR MOUNTING
Texte : The Art et marges museum will be closed from 10/13 to 10/22 for the new exhibition's mounting. The exhibition will be open from Thursday 10/22 to Sunday 04/25/2021.

YOU ARE INVITED TO PARTY WITH US on Thursday 10/22 from 4 p.m. to 9 p.m.! OPENING of the Embrasez-vous ! anniversary exhibition in the presence of the artists and PUBLICATION-SALE of the “Art et marges museum” publication.
Reservation at accueil@artetmarges.be. Fill in: Subject - VERNISSAGE, contact, number of visitors and desired time slots: 45 min per slots, every hour from 4 p.m. to 8 p.m.

**Comment by ninwille** [comment]
Hello, j'ai changé rapidement pour que tu puisses voir à quoi ça ressemble, à voir si c'est mieux que le texte de fermeture soit sur le fond coloré, et/ou que l'introduction reste au dessus...?

**Comment by FredericOszczak** [comment]
On peut tout mettre sur l'image je pense ! Merci beaucoup !
