### ISSUE TITLE
modification dans http://www.artetmarges.be/collection/fr/yassir-amazine.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#931]
remplacer image par
![amazineicone](https://user-images.githubusercontent.com/22938933/95678892-be133e00-0bcf-11eb-811a-7b2e6c7c09b7.jpg)

**Comment by ninwille** [comment]
Hello, quand il y a beaucoup d'images à changer, c'est plus simple si vous m'envoyez les images dans un dossier (un .zip ou via wetransfer si c'est trop lourd). ça évite de devoir les télécharger une à une, et changer leur nom à chaque fois (car ne portent plus leur nom d'origine après être passées par git). Les noms des images devraient correspondre aux noms qui se trouvent dans le fichier excel que je vous avais envoyé (avec la liste des artistes). Le nom peut être adapté soit en changeant le nom de l'image soit en changeant son nom dans le fichier excel, mais en tout cas les deux doivent correspondre (et si vous modifiez l'excel il faut évidemment me le renvoyer). C'est le même dossier d'images qui est utilisé pour les 3 langues, donc ce n'est pas utile de faire plusieurs issues pour cela. Désolée si les choses se disent au fur et à mesure, de mon côté je ne sais pas ce qui a été partagé chez vous...peut-être ça vaudrait la peine de consigner tous ces fonctionnement à un endroit :)

**Comment by FredericOszczak** [comment]
Hello Nina, 

Ok c'est noté, est-ce que tu veux qu'on refasse tout du coup ? C'est une stagiaire qui s'est occupée de cela. Je suis en train de rédiger un guide de la communication, je suis preneuse de toutes les infos possibles pour te/nous faciliter l'utilisation de cette plateforme !! 

Merci beaucoup pour ton aide ! Belle après-midi,

Marcelline

**Comment by ninwille** [comment]
Oui, bien sur, voici! (je les ai envoyé par mail aussi)
[collection-all.zip](https://github.com/communicationartetmarges/art-et-marges/files/5372266/collection-all.zip)

**Comment by ninwille** [comment]
Pour le fait de le refaire, si vous avez les ressources chez vous ça sera plus simple. Si c'est compliqué dis-moi, on peut repasser à travers le tout, mais ça va nous prendre un peu de temps.

**Comment by FredericOszczak** [comment]
Je peux m'en occuper seulement la semaine du 26, ma stagiaire vient de finir son stage et nous sommes en plein dans la nouvelle expo qui ouvre le 22 :O ! 
Si vous n'avez pas le temps, je le ferais donc plus tard sinon si vous pouvez le faire ça serait aussi top :) Tiens moi au courant et belle soirée !

**Comment by ninwille** [comment]
Hello, désolée j'ai raté ce dernier message. Nous ne l'avons donc pas fait... Et sommes plutôt chargés pour le moment. Si je vois du temps qui se dégage je te préviendrai.

**Comment by FredericOszczak** [comment]
Est-ce que tu peux me dire le poids maximum que peuvent faire les photos des oeuvres quand on clique dessus pour un affichage optimum qui ne rame pas ? Certaines sont d'une super mauvaise qualité j'aimerais bien les changer ! Merci :)

**Comment by ninwille** [comment]
@pacomski : peut-être sais-tu mieux répondre que moi à cette question?

**Comment by FredericOszczak** [comment]
Hello Nina ! 

- Voici les visuels à changer. Je t'envoie des ZIP par Smash pour les icônes et un pour les visuels des pages. 
- Voici les liste mises à jour. En revanche en CVS les couleurs ne s'affichent pas donc mes changements ne sont pas visibles... 
En résumé : 
- J'ai renommé toutes les images comme je te les ai envoyé. 
- Cécile FRANCEUS devient Cecile
- Il y avait pas mal de fautes d'espace entre les tirets des dates de vie ; je les ai remis à jour : il ne doit pas y avoir d'espace (ex. 1960-2007) 
- Les nom à particule doivent être tous en majuscule par cohérence il y en avait trois dont ce n'était pas le cas (De Smedt, de vries et di giovanni)

Voilà, n'hésites pas si tu as des questions !

**Comment by FredericOszczak** [comment]
https://fromsmash.com/Images-et-tableaux-collection et voici le lien !

**Comment by ninwille** [comment]
Hello, merci! Désolée pour le délais, je m'occupe de ça vendredi!

**Comment by ninwille** [comment]
Hello, j'ai enfin pu m'occuper de cette mise à jour.
Pour la suite, pas de soucis si les changements du CSV ne s'affichent pas, je remplace simplement l'ancien fichier par le nouveau.
Par contre, il faut que les noms des thumbnails (les 'vignettes') soient les mêmes que les images correspondant au même artiste. J'ai du en renommer pas mal. 
Par ailleurs, il ne faut jamais utiliser de virgule dans les noms de fichiers, ni d'autres signes autre que '_' (ou éventuellement des '-'). Il vaut également mieux éviter les accents. Il y avait des fichiers qui n'étaient pas reconnus à cause de tout ça, je les ai renommé également.
Je te renvoie donc les CSV pour que tu aies la dernière version. 
De façon général je les mets toujours à jour là: https://
[collection-all-.zip](https://github.com/communicationartetmarges/art-et-marges/files/5578135/collection-all-.zip)
github.com/communicationartetmarges/art-et-marges/tree/master/templates

J'espère que tout est fonctionnel, j'avoue que je n'ai pas été vérifier tous les artistes. Si tu vois un soucis n'hésite pas à relayer!

**Comment by FredericOszczak** [comment]
Hello Nina ! 

Merci beaucoup ! Je note toutes les remarques que tu fais pour les personnes qui géreront le poste après qu'il n'y ait plus de confusions et que ça soit efficace pour vous et nous ! En attendant désolée de toutes ces petites erreurs qui traînent et merci pour ton aide et ta patience ! 

J'ai pour l'instant remarqué des problèmes sur les images de : Heide de Bruyne, Tomoaki Sakai dont tu trouveras les images à mettre en vignette et dans la page pj ici : 
[Archive.zip](https://github.com/communicationartetmarges/art-et-marges/files/5590582/Archive.zip)
De plus, dans la version française JACQUELINE VIZCAÏNO n'apparait pas.

**Comment by ninwille** [comment]
Hello, voilà qui est corrigé. 
Viscaino n'apparaissait pas parce qu'elle n'était pas dans le csv, je l'ai ajoutée :)
N'hésite pas s'il y a d'autres éléments à adapter!
J'en profite pour ajoute que les espaces sont aussi à éviter dnas les noms d'images :)
Bonne après-midi!
