### ISSUE TITLE
Récupération http://www.artetmarges.be/fr/index.html

### ISSUE THREAD

**Issue by FredericOszczak** [communicationartetmarges/art-et-marges#999]
Hello Nina ! 

Est-ce possible de récupérer les infos **dans les trois langues** qu'il y avait pour l'expo **Le Cœur au ventre** afin de les faire passer dans la partie **Exposition - Expositions passées** s'il te plait ?
Donc le visuel, le petit texte de présentation, le dossier de presse et le dossier pédagogique ? 

[dossier pédagogique_Le coeur au ventre_OK.pdf](https://github.com/communicationartetmarges/art-et-marges/files/5371881/dossier.pedagogique_Le.coeur.au.ventre_OK.pdf)
[dossier de presse.pdf](https://github.com/communicationartetmarges/art-et-marges/files/5371882/dossier.de.presse.pdf)

**Comment by ninwille** [comment]
Hello, oui désolée, normalement je le fais d'office, petit oubli de ma part! Par contre le diapo ne passe pas dans la colonne de droite, du coup j'ai remis l'ancienne image. Si tu préfère la bannière qui est dans le diapo dis-moi.
